EOY 2023: top five podcasts story
Automattic/pocket-casts-ios pull request #1157
Opened 2023-10-10 16:55 UTC by leandroalonso

| 📘 Part of: #1142 | 🎨 Designs: [Figma](https://www.figma.com/file/lH66LwxxgG8btQ8NrM0ldx/End-of-Year?type=design&node-id=1599-20385&mode=design) |
|:---:|:---:|

Adds the 2023 visual for the Top Podcasts Story.

**Animations are not part of this task and will be tackled later.**

<img src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/7ba5bc7f-92f7-4089-a394-ae49e09d5538" width="300">

## To test

1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile > Settings > Beta Features > enable `endOfYear`
3. Go back to Profile
4. Tap the EOY image
5. Skip to the fourth story
5. ✅ Check that the story looks good
6. Tap "Share this story" > Save Image
7. Go to Photos
8. ✅ The story image asset should be the last one on Photos and should have your top five podcasts

Please test on a big device (iPhone 15 Pro Max, for example), a normal device (iPhone 15), and a smaller device (iPod touch).

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-10-10 21:14 UTC, emilylaguna requested changes
Looking good! However, I noticed on the iPod Touch the text seems really large which ends up clipping some text. 

<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/b4798fe4-186d-4a2c-a46a-52910f8c9d4e" width="320" />

When compared to the other devices (iPhone 14, etc) it doesn't seem as big.

2023-10-11 20:08 UTC, leandroalonso commented
> When compared to the other devices (iPhone 14, etc) it doesn't seem as big.

Ops, forgot to add relative font sizes, done in 045f23e0b8077675e8cf79e1a615c65d64049497

> Another I noticed is when I dismiss from this view, the top right gradient shows as its being dismissed:

I fixed that on the next PR: #1161

2023-10-13 12:30 UTC, CookieyedCodes commented
@leandroalonso I know this might be set in stone now but I think the fact that your a podcast app, you should consider doing a top 10-15 😅,top 5 seems limiting when the major thing you do is podcasts 🤔 😅

2023-10-13 16:42 UTC, leandroalonso commented
@CookieyedCodes thanks for your suggestion! I'll pass along the feedback to the team.

2023-10-19 03:00 UTC, emilylaguna approved these changes

2023-10-19 13:38 UTC, merged