Playback 2023: entry point
Automattic/pocket-casts-ios pull request #1169
Opened 2023-10-16 16:30 UTC by leandroalonso

| 📘 Part of: #1142 | 🎨 Designs: [Figma](https://www.figma.com/file/lH66LwxxgG8btQ8NrM0ldx/End-of-Year?type=design&node-id=1599-20385&mode=design) |
|:---:|:---:|

Updates the logic and visuals for the Playback 2023 modal, profile badge, and profile card.

| Modal | Badge | Card |
| ------ | ------ | ----- |
| ![Simulator Screenshot - iPhone 15 - 2023-10-16 at 13 20 43](https://github.com/Automattic/pocket-casts-ios/assets/7040243/6ef00ee4-b09e-497f-b05c-15ebe1107616) | ![Simulator Screenshot - iPhone 15 - 2023-10-16 at 13 19 18](https://github.com/Automattic/pocket-casts-ios/assets/7040243/4a8c4f5f-4557-4655-8129-839bd2741a6a) | ![Simulator Screenshot - iPhone 15 - 2023-10-16 at 13 19 26](https://github.com/Automattic/pocket-casts-ios/assets/7040243/a2ae75c4-3b77-459b-afbb-3ec99f0a3655) |

## To test

1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile > Settings > Beta Features > enable `endOfYear`
3. Restart the app
4. ✅ A modal should be shown
5. ✅  Tapping on "View My 2023" shows the stories
6. Dismiss it
7. ✅ There should be a badge on the "Profile" tab
8. Tap it
9. ✅ The badge should disappear
10. ✅ Check that there's a card on Profile prompting you to see your 2023
11. Tap it
12. ✅ Playback 2023 stories should start

If you want to reset the modal being shown and badge, go to Profile > Settings > Developer > Reset modal/profile badge

Please test on a big device (iPhone 15 Pro Max, for example), a normal device (iPhone 15), and a smaller device (iPod touch). Also on light/dark mode.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-10-19 06:02 UTC, emilylaguna requested changes
Nice work. Left some comments. 

Also, I noticed that if I'm logged out and I tap go to open the EOY I am brought to the old login view.

2023-10-19 06:02 UTC, emilylaguna commented on podcasts/End of Year/Views/EndOfYearModal.swift
> +                    .font(style: .body, weight: .medium, maxSizeCategory: .accessibilityMedium)
The font size is a bit too big, and the linespacing a bit tight when compared to the designs. 


![Screenshot 2023-10-19 at 1 54 55 AM](https://github.com/Automattic/pocket-casts-ios/assets/793774/72c35922-f304-4af7-8ba9-933cd347919d)

2023-10-19 16:25 UTC, leandroalonso commented on podcasts/End of Year/Views/EndOfYearModal.swift
> +                    .font(style: .body, weight: .medium, maxSizeCategory: .accessibilityMedium)
Changed in 397f81eccb89bc2590ee94ffaabfd3d514c075fc

2023-10-19 16:26 UTC, leandroalonso commented
> Also, I noticed that if I'm logged out and I tap go to open the EOY I am brought to the old login view.

This is already a task in #1142 :)

2023-10-31 14:44 UTC, emilylaguna requested changes
On the iPad the sheet is clipped in both landscape and portrait. 
 
<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/69d2244d-06bc-4439-8ba6-15ea929efffa" width="320" />

2023-10-31 16:34 UTC, leandroalonso commented
@emilylaguna fixed in 6f790846f26b509ed0770bd2fb07513394ead5fd

2023-11-06 23:05 UTC, emilylaguna approved these changes

2023-11-07 13:21 UTC, merged