Playback 2023: year over year listening time story
Automattic/pocket-casts-ios pull request #1174
Opened 2023-10-18 14:05 UTC by leandroalonso

| 📘 Part of: #1142 | 🎨 Designs: [Figma](https://www.figma.com/file/lH66LwxxgG8btQ8NrM0ldx/End-of-Year?type=design&node-id=1599-20385&mode=design) |
|:---:|:---:|

Adds the 2023 visual for the Year Over Year Listening Time Story.

<img src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/12e9b332-cffe-47f8-9406-8820ced3e4e8" width="300">

**This doesn't tackle syncing 2022 listening history.**

## To test

## Different states

1. Go to `YearOverYearstory.swift`
2. Preview the view
3. ✅ Go over all the cases and check that their match the designs
4. You can also play with the numbers to see if the bars/title updates accordingly

## Story appearing

1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile > Settings > Beta Features > enable `endOfYear`
3. Go back to Profile
4. Tap the EOY image
5. Skip to the penultimate story
5. ✅ Check that the story looks good compared to the design
6. Tap "Share this story" > Save Image
7. ✅ You should go back to the first story
8. Go to Photos
9. ✅ The story image asset should be the last one in Photos

Please test on a big device (iPhone 15 Pro Max, for example), a normal device (iPhone 15), and a smaller device (iPod touch).

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-10-18 14:12 UTC, leandroalonso commented on podcasts/End of Year/Stories/YearOverYearStory.swift
> +    let identifier: String = "year_over_year"
@ashiagr I defined the identifier of this story as `year_over_year`. Open to suggestions if you have any other ideas. :)

2023-11-01 12:06 UTC, emilylaguna requested changes
Nice work, left some comments to improve the code below.

2023-11-01 12:06 UTC, emilylaguna commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                                            lastPlaybackInteractionDate IS NOT NULL AND lastPlaybackInteractionDate BETWEEN strftime('%s', '2021-01-01') and strftime('%s', '"2023-01-01"')
Should this be between 2022-01-01 and 2023-01-01?

2023-11-01 12:06 UTC, emilylaguna commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                                            lastPlaybackInteractionDate IS NOT NULL AND lastPlaybackInteractionDate BETWEEN strftime('%s', '2021-01-01') and strftime('%s', '"2023-01-01"')
My stats were showing that I didn't listen to anything. 

```suggestion
                                            lastPlaybackInteractionDate IS NOT NULL AND lastPlaybackInteractionDate BETWEEN strftime('%s', '2021-01-01') and strftime('%s', '2023-01-01')
```

2023-11-01 12:06 UTC, emilylaguna commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                let query = "SELECT DISTINCT \(DataManager.episodeTableName).uuid, SUM(playedUpTo) as totalPlayedTime from \(DataManager.episodeTableName) WHERE \(listenedEpisodesThisYear) UNION SELE
If the user doesn't have any listening history for the previous year, then the result will be:

Note: I modified the query to return the label to show the order better.

![Screenshot 2023-10-31 at 2 46 14 PM](https://github.com/Automattic/pocket-casts-ios/assets/793774/de5bf10b-d4a1-46a8-a85a-af3fdc95b32e)

When using `UNION` the order of the queries is not preserved, so it's not guaranteed the first item will always be 2023, and the second 2022. 

Using to using `UNION ALL` will preserve the order regardless of the values:


![Screenshot 2023-10-31 at 2 56 58 PM](https://github.com/Automattic/pocket-casts-ios/assets/793774/8c45052a-854f-4e50-984a-12852d512e55)


---

```suggestion
                let query = "SELECT DISTINCT \(DataManager.episodeTableName).uuid, SUM(playedUpTo) as totalPlayedTime from \(DataManager.episodeTableName) WHERE \(listenedEpisodesThisYear) UNION ALL SELECT DISTINCT \(DataManager.episodeTableName).uuid, SUM(playedUpTo) as totalPlayedTime from \(DataManager.episodeTableName) WHERE \(listenedEpisodesPreviousYear)"
```

2023-11-01 12:06 UTC, emilylaguna commented on podcasts/End of Year/EndOfYearStoriesBuilder.swift
> +                yearOverYearListeningTime.totalPlayedTimeLastYear != 0 {
We can't compare if we don't have history for both years, so we should hide the story. 

```suggestion
            if yearOverYearListeningTime.totalPlayedTimeThisYear != 0 &&
                yearOverYearListeningTime.totalPlayedTimeLastYear != 0 {
```

2023-11-01 12:06 UTC, emilylaguna commented on podcasts/End of Year/Stories/YearOverYearStory.swift
> +    let yearOverYearListeningTime: YearOverYearListeningTime
Can we rename this to just `data` since it's already relative to the story which is named year over year?


```suggestion
    let data: YearOverYearListeningTime
```

2023-11-01 12:06 UTC, emilylaguna commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +        return (nonRoundendPercentage.rounded() * 100) / 100
This looks like we're calculating the percent change between this and last years listening number. 

Wouldn't it be the same to do:

```suggestion
        (((totalPlayedTimeThisYear - totalPlayedTimeLastYear) / totalPlayedTimeLastYear) * 100).rounded()
```

2023-11-01 12:06 UTC, emilylaguna commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +        return (nonRoundendPercentage.rounded() * 100) / 100
Also since we're using this in 4 different places in the view, and the values aren't going to change could this to be calculated in init and stored?

2023-11-01 12:06 UTC, emilylaguna commented on podcasts/End of Year/Stories/YearOverYearStory.swift
> +        }
We can achieve the same effect without the `where` by doing:

```suggestion
        switch yearOverYearListeningTime.percentage {
        case .infinity:
            L10n.eoyYearOverYearTitleSkyrocketed
        case 10...:
            L10n.eoyYearOverYearTitleWentUp("\(yearOverYearListeningTime.percentage.clean)%")
        case ...0:
            L10n.eoyYearOverYearTitleWentDown
        default:
            L10n.eoyYearOverYearTitleFlat
        }
```

2023-11-01 12:06 UTC, emilylaguna commented on podcasts/End of Year/Stories/YearOverYearStory.swift
> +        }
We can achieve the same result a bit cleaner without the `where`:
 
```suggestion
        switch yearOverYearListeningTime.percentage {
        case 10...:
            L10n.eoyYearOverYearSubtitleWentUp
        case ...0:
            L10n.eoyYearOverYearSubtitleWentDown
        default:
            L10n.eoyYearOverYearSubtitleFlat
        }
```

2023-11-01 14:13 UTC, leandroalonso commented on podcasts/End of Year/EndOfYearStoriesBuilder.swift
> +                yearOverYearListeningTime.totalPlayedTimeLastYear != 0 {
We can't compare but we'll show it, we'll display the previous year as "0 minutes listened". ([discussed here](https://a8c.slack.com/archives/C041BGTFQ5R/p1697573573229879))

2023-11-01 14:13 UTC, leandroalonso commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                                            lastPlaybackInteractionDate IS NOT NULL AND lastPlaybackInteractionDate BETWEEN strftime('%s', '2021-01-01') and strftime('%s', '"2023-01-01"')
I fixed that on an upcoming PR but did it here: b8bc790f66077a82855fc126ae594b6601af8768

2023-11-01 14:14 UTC, leandroalonso commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                                            lastPlaybackInteractionDate IS NOT NULL AND lastPlaybackInteractionDate BETWEEN strftime('%s', '2021-01-01') and strftime('%s', '"2023-01-01"')
Fixed in b8bc790f66077a82855fc126ae594b6601af8768

2023-11-01 14:28 UTC, leandroalonso commented on podcasts/End of Year/Stories/YearOverYearStory.swift
> +    let yearOverYearListeningTime: YearOverYearListeningTime
Done in 4b40128a13db3db5b98e0a3b35eb1f9444c7ffc6

2023-11-01 14:28 UTC, leandroalonso commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +        return (nonRoundendPercentage.rounded() * 100) / 100
Done in b344100174bf440aeb2f3e6d27192b0574a44e84

2023-11-06 23:42 UTC, emilylaguna approved these changes

2023-11-07 13:22 UTC, merged