Playback 2023: purchase flow
Automattic/pocket-casts-ios pull request #1189
Opened 2023-10-30 13:42 UTC by leandroalonso

| 📘 Part of: #1142 | 🎨 Designs: [Figma](https://www.figma.com/file/lH66LwxxgG8btQ8NrM0ldx/End-of-Year?type=design&node-id=1599-20385&mode=design) |
|:---:|:---:|

Add the purchase flow for Plus stories. It also updates logic so the old login flow is not shown. 

https://github.com/Automattic/pocket-casts-ios/assets/7040243/6e07380a-2257-4fb9-96f8-e8caf82fcd00

Ps.: This does not implement the 2022 syncing.

## To test

## Correct login flow

1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile > Settings > Beta Features > enable `endOfYear`
3. Log out
3. Go back to Profile
4. Tap the EOY image
5. ✅ The current onboarding flow should be displayed — not the old one

## Paid story for non-paid users

1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile > Settings > Beta Features > enable `endOfYear`
3. Go back to Profile
4. Tap the EOY image
5. Skip to the 8th story
6. Tap "Start your free trial"
7. ✅ The purchase flow should be displayed
8. Complete the purchase
9. ✅ The flow should dismiss and the story should be available
10. Repeat the steps above with `patron` feature flag enabled

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-11-01 20:18 UTC, emilylaguna requested changes
Nice work. Left a couple comments.

2023-11-01 20:18 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
> +        )
I feel like we can just use the `ultraThinMaterial` as the background without the gradient which allows more of the background to show through but still ensures the text is legible:

| Before | After |
|:---:|:---:|
|<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/928a94ef-2e09-4b3e-ae08-4acac912466f" width="320" />|<img src="https://github.com/Automattic/pocket-casts-ios/assets/793774/8d8b1992-9163-4a45-903f-646466e35280" width="320" />|


```suggestion
        .background(.ultraThinMaterial)
        .environment(\.colorScheme, .dark)
```

2023-11-01 20:18 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusPurchaseModel.swift
> +
Should we make this more generalized and add it as a flag like we did with the [shouldDismiss check in the OnboardingFlow](https://github.com/Automattic/pocket-casts-ios/blob/ae46fed9d26748f106c04db3cc041851fb2ef503/podcasts/Onboarding/OnboardingFlow.swift#L123)?

That way in the future if there are more flows that we want to do this with it will be easier to do.

2023-11-01 20:18 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
> +                Button(L10n.eoyStartYourFreeTrial) {
This is a tricky one since there is a chance the user isn't eligible for the free trial anymore, or we stop offering it. So this would say start free trial, but in the upgrade view it won't be an option. 

The fix for this is to use the `PlusPricingInfoModel` and check the `pricingInfo.hasFreeTrial` value:

```
struct PaidStoryWallView: View {
    @StateObject private var model = PlusPricingInfoModel()

    var body: some View {
        ...
        Button(model.pricingInfo.hasFreeTrial ? L10n.eoyStartYourFreeTrial : L10n.upgradeToPlan(L10n.pocketCastsPlusShort)) {
        }
        ...
    } 
}
```

2023-11-01 20:28 UTC, leandroalonso commented on podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
> +                Button(L10n.eoyStartYourFreeTrial) {
cc @ashiagr

2023-11-01 21:18 UTC, leandroalonso commented on podcasts/Onboarding/Models/PlusPurchaseModel.swift
> +
Done in 885769d66270ebaac7f7313b30a3b643b0e893ef

2023-11-01 21:18 UTC, leandroalonso commented on podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
> +                Button(L10n.eoyStartYourFreeTrial) {
Done in ecf79bc7895f5716eae9d5ed13efdef8448f4e1b

2023-11-08 13:20 UTC, leandroalonso commented
@emilylaguna could you please 👀 again?

2023-11-08 15:03 UTC, emilylaguna approved these changes

2023-11-08 15:32 UTC, merged