Cache the EndOfYear.isEligible value
Automattic/pocket-casts-ios pull request #1287
Opened 2023-12-11 21:40 UTC by emilylaguna

This adds a `EligibilityChecker` class to manage the `isEligible` value. It will update the value when:
- A sync is completed
- The user signs in
- The playback was paused, ended, or changed

Doing this prevents `DataManager.sharedManager.isEligibleForEndOfYearStories` from being called too often from places like the ProfileViewController. 

A future PR will address how the `ProfileViewController` is update the values to reduce the calls.

## To test

1. Fresh install the app
2. ✅ Verify you do not see the card on the profile tab
3. Sign into an account that is eligible for Playback 2023
4. ✅ Verify the prompt appears after signing in
5. ✅ Verify you see the card on the profile tab
6. Fresh install the app again
7. Play and finish an episode
8. Go to the Profile tab
9. ✅ Verify you see the Playback card
10. Relaunch the app
11. ✅ Verify you see the prompt

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-12-11 21:45 UTC, pocketcasts commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/36">7.53</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-12-12 14:23 UTC, leandroalonso requested changes

2023-12-12 14:23 UTC, leandroalonso commented on podcasts/End of Year/EndOfYear.swift
> +                notificationCenter.addObserver(forName: $0, object: nil, queue: updateQueue) { [weak self] notification in
The app is freezing for me due to the use of `OperationQueue`. I wasn't able to found out why though. :(

Here are the steps to reproduce:

1. Clean install
2. Play any episode
3. Move the scrubber
4. Pause
5. 🥶 

Here's a video showing that:

https://github.com/Automattic/pocket-casts-ios/assets/7040243/184724e8-2e45-4de7-a8c1-b78524a06148

If I change `updateQueue` to `.main` it works just fine.

2023-12-12 14:23 UTC, leandroalonso commented on podcasts/End of Year/EndOfYear.swift
> +            let isEligible = DataManager.sharedManager.isEligibleForEndOfYearStories()
I think we should only care when the `isEligible` is `false`. If it's `true`, it shouldn't change (even by logging out, given the database data is not erased).

So I think we can add a `guard` statement:

```
            guard !isEligible else {
                return
            }
```

2023-12-12 14:24 UTC, leandroalonso commented
@emilylaguna I think we can target `release/7.54` instead of `trunk` so we can test that throughout the next few days.

2023-12-12 15:16 UTC, emilylaguna commented on podcasts/End of Year/EndOfYear.swift
> +                notificationCenter.addObserver(forName: $0, object: nil, queue: updateQueue) { [weak self] notification in
Weird. I've updated that here: 12c036919e9e0bae34b3601af0a081b8efc16e27

2023-12-12 15:16 UTC, pocketcasts commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/36">7.53</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-12-12 17:17 UTC, emilylaguna commented
> I think we can target release/7.54 instead of trunk so we can test that throughout the next few days.

Updated.

2023-12-12 17:23 UTC, leandroalonso approved these changes

2023-12-12 17:28 UTC, merged