[1304] Remove patron feature flag.
Automattic/pocket-casts-ios pull request #1321
Opened 2024-01-03 15:05 UTC by SergioEstevao

Fixes #

This remove the patron feature flag and code branching associated with it.

## To test

 - Start the Pocket Cast app
 - Go to settings
## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-01-03 15:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=1321) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=1321) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-ios?pullRequest=1321) it.</sub>

2024-01-03 15:10 UTC, pocketcasts commented
<!--
  0 Errors
  2 Warnings: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/38">7.55</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-01-04 16:14 UTC, leandroalonso requested changes
@SergioEstevao the `patron` flag was also a remote feature flag. There's code for it here: https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/AppDelegate.swift#L302

Your PR is green because of the `#if !DEBUG` flag. So we also need to:

1. Remove this code from there
2. Remove the remote feature flag from Firebase

2024-01-04 16:16 UTC, leandroalonso commented
[nit]

Also, about the title of your PR, Emily has been using "Cleanup: description" [in the past](https://github.com/Automattic/pocket-casts-ios/pulls?q=is%3Apr+is%3Aclosed+Cleanup%3A+). I think we can do the same here to keep everything grouped. :)

2024-01-04 16:50 UTC, SergioEstevao commented
> Remove the remote feature flag from Firebase

When you say that is it to go to Firebase and remove it or just delete the code in `configureFirebase()`

```Constants.RemoteParams.patronEnabled: NSNumber(value: Constants.RemoteParams.patronEnabledDefault),```

2024-01-04 17:05 UTC, leandroalonso commented
@SergioEstevao both!

2024-01-04 18:11 UTC, leandroalonso commented on podcasts/AppDelegate.swift
> -            try FeatureFlagOverrideStore().override(FeatureFlag.patron, withValue: Settings.patronEnabled)
There are still some more code we can remove:

- https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/Settings.swift#L897
- https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/Constants.swift#L327-L328

2024-01-04 18:11 UTC, leandroalonso requested changes
@SergioEstevao I tested all the mentioned scenarios plus a few additional ones and it all works as expected.

There are just a few more codes we can remove before merging this. :)

2024-01-04 20:13 UTC, leandroalonso approved these changes

2024-01-05 11:33 UTC, merged