[Tracks] Track on play/pause the content type
Automattic/pocket-casts-ios pull request #1379
Opened 2024-01-29 14:30 UTC by leandroalonso

When tracking play/pause events, add a property to inform whether it's video or audio.

## To test

1. Play any audio podcast
2. ✅ `🔵 Tracked: playback_pause ["content_type": "audio", "source": "?"]` should be tracked (`source` will vary depending from whether did you played)
3. Play a video podcast (eg.: Twit News (Video))
4. ✅ `🔵 Tracked: playback_pause ["content_type": "video", "source": "?"]` should be tracked (`source` will vary depending from whether did you played)

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-01-29 15:32 UTC, emilylaguna requested changes
Thanks for tackling this, can we update this to be included on the other playback events as well?

2024-01-29 15:48 UTC, leandroalonso commented
@emilylaguna ops, changed in 69492f67196cbfb182f015f9d344b5b70d261e4f

2024-01-31 22:16 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/40">7.57</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-05 19:28 UTC, emilylaguna approved these changes

2024-02-07 19:30 UTC, merged