Update account upgrade modal
Automattic/pocket-casts-ios pull request #1394
Opened 2024-02-01 17:38 UTC by SergioEstevao

Fixes #

This PR updates the account upgrade model to match the Android designs

## To test

Steps to test your PR.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-02-01 17:40 UTC, dangermattic commented
<!--
  0 Errors
  3 Warnings: View files have been modified,...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/40">7.57</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-ios</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-06 14:37 UTC, mebarbosa reviewed
Hey @SergioEstevao 👋🏽 Nice work! 🚀 

Shouldn't we use 'Subscribe to Pocket Casts Plus' instead of 'Become a Plus member and unlock all Pocket Casts features'? I've checked Figma, and it's showing 'Subscribe to Pocket Casts Plus.

Maybe I am missing something

2024-02-06 16:48 UTC, SergioEstevao commented
@david-gonzalez-a8c , can you confirm the title strings for Plus and Patron for the modal?

And the way we want to show the prices, with strike-through or not?

2024-02-06 17:24 UTC, david-gonzalez-a8c commented
Let's do "Subscribe to Plus" / "Subscribe to Patron" and show the discounted price directly, no old price with strike-through

2024-02-07 03:32 UTC, emilylaguna requested changes
Nice work. I left some comments below, let me know what you think.

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusButtonStyles.swift
> +                color.cornerRadius(800)
We can use the clipShape to achieve the same effect:

```suggestion
                color.clipShape(.capsule)
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusPurchaseModal.swift
> +                                            OfferLabel(offerDescription, plan: coordinator.plan, isSelected: selectedOption ==   product.identifier)
```suggestion
                                            OfferLabel(offerDescription, plan: coordinator.plan, isSelected: selectedOption == product.identifier)
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusPurchaseModal.swift
> +        .fixedSize(horizontal: false, vertical: true)
A few things here:
- [`foregroundColor`](https://developer.apple.com/documentation/SwiftUI/View/foregroundColor(_:)) is being deprecated so we should use `foregroundStyle` instead
- The link color is using the default color, we can change this by using `.tint(.textColor)`.
- I noticed the font size was slightly smaller than the designs and should be centered not leading aligned. 

```suggestion
        .multilineTextAlignment(.center)
        .foregroundStyle(Color.textColor)
        .tint(.textColor)
        .font(size: 14, style: .subheadline)
        .fixedSize(horizontal: false, vertical: true)
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusPurchaseModal.swift
> +            Text(.init("[\(purchaseTerms[safe: 3] ?? "")](\(termsOfUse))")).underline()
Nit: We can prevent the Privacy Policy and Terms and Conditions links from splitting between lines by using `nonBreakingSpaces()` which replaces the spaces with [non-breaking](https://en.wikipedia.org/wiki/Non-breaking_space) ones. 

```suggestion
            Text(purchaseTerms[safe: 0] ?? "") +
            Text(.init("[\(purchaseTerms[safe: 1]?.nonBreakingSpaces() ?? "")](\(privacyPolicy))")).underline() +
            Text(purchaseTerms[safe: 2] ?? "") +
            Text(.init("[\(purchaseTerms[safe: 3]?.nonBreakingSpaces() ?? "")](\(termsOfUse))")).underline()
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
> +            sheetPresentationController.detents = detents
```suggestion
            sheetPresentationController.detents = UIScreen.isSmallScreen ? [.large()] : [.medium()]
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
> +        let controller = PlusPurchaseModel.make(in: parentController, plan: product.identifier.plan, selectedPrice: .yearly)
When creating the view directly it causes the analytics to be missing the properties:

`🔵 Tracked: select_payment_frequency_shown ["flow": "none"]`

We should instead create it using `OnboardingFlow.shared.begin` and specifying the `.plusAccountUpgrade` value. 

```suggestion
        let context: OnboardingFlow.Context? = ["product": ProductInfo(plan: product.identifier.plan, frequency: .yearly)]
        let controller = OnboardingFlow.shared.begin(flow: .plusAccountUpgrade, in: parentController, source: source.rawValue, context: context)
```

We should then update the [OnboardingFlow .plusAccountUpgrade handler](https://github.com/Automattic/pocket-casts-ios/blob/feature/update_account_purchase_modal/podcasts/Onboarding/OnboardingFlow.swift#L24-L26) to:

```
        case .plusAccountUpgrade:
            self.source = source ?? "unknown"
            let product = context?["product"] as? ProductInfo

            flowController = PlusPurchaseModel.make(in: controller,
                                                    plan: product?.plan ?? .plus,
                                                    selectedPrice: product?.frequency ?? .yearly)
```

We can then validate the events include the correct information:
`🔵 Tracked: select_payment_frequency_shown ["source": "account_details", "flow": "plus_account_upgrade"]`

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusPricingInfoModel.swift
> +        }
[nit]

```suggestion
        var hasOffer: Bool {
           products.contains(where: { $0.offer != nil } )
        }
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusPurchaseModal.swift
> +        return price
Instead of using the nested if's what about using a guard + switch?

```suggestion
        guard let offer = subscriptionInfo.offer else {
            return subscriptionInfo.price
        }

        let period = subscriptionInfo.identifier.productInfo.frequency.description

        switch offer.type {
        case .freeTrial:
            return L10n.subscriptionFrequencyPricingFormat(subscriptionInfo.rawPrice, period)
        case .discount:
            return L10n.subscriptionFrequencyPricingFormat(offer.price, period)
        }
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
> +
```suggestion
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
> +                    .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
```suggestion
                    .clipShape(.capsule)
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/UIScreen+Sizes.swift
> +        return UIScreen.main.bounds.height < 667
[nit]

```suggestion
       UIScreen.main.bounds.height < 667
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/IAPHelper.swift
> +
```suggestion

```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusPricingInfoModel.swift
> +                return L10n.pricingTermsAfterDiscount(rawPrice, duration, dateAfterOffer )
If we switch to using the `.long` format, we can use the nonBreakingSpaces() to prevent it from being split across multiple lines. 

```suggestion
                return L10n.pricingTermsAfterTrialLong(duration, dateAfterOffer.nonBreakingSpaces())
            case .discount:
                return L10n.pricingTermsAfterDiscount(rawPrice, duration, dateAfterOffer.nonBreakingSpaces())
```

2024-02-07 03:32 UTC, emilylaguna commented on podcasts/IAPHelper.swift
> +        return date?.formatted(date: .numeric, time: .omitted)
Looking at the designs, it looks like the date displayed is in a longer form. Wdyt about changing this to long?

```suggestion
        return date?.formatted(date: .long, time: .omitted)
```

2024-02-07 09:41 UTC, SergioEstevao commented
@emilylaguna thanks for the great review, I updated the code can you give it another look? Thanks.

2024-02-07 19:03 UTC, emilylaguna requested changes
Awesome, thanks for making those changes. I left 1 more comment below, and also I found that if purchase a subscription the modal gets stuck open with the error:

```
 Attempt to present <UINavigationController: 0x13916e000> on <podcasts.MainTabBarController: 0x139829600> (from <podcasts.AccountViewController: 0x15854f8c0>) which is already presenting <_TtGC8podcasts36OnboardingModalHostingViewControllerGV7SwiftUI15ModifiedContentVS_17PlusPurchaseModalVS_17ThemedEnvironment__: 0x13a13c1e0>.
```

This is because the handle next logic doesn't check for the presented view, and can be fixed by updating `PlusPurchaseModel.handleNext` on line 168 from:

```
        // Dismiss the current flow
        presentNextBlock()
```

to 

```
        // Dismiss the current flow
        if parentController.presentedViewController != nil {
            parentController.dismiss(animated: true, completion: presentNextBlock)
        } else {
            presentNextBlock()
        }
```

2024-02-07 19:03 UTC, emilylaguna commented on podcasts/UIScreen+Sizes.swift
> +       UIScreen.main.bounds.height < 667
On the iPhone SE this returns false because its height is 667. 

```suggestion
       UIScreen.main.bounds.height <= 667
```

2024-02-07 20:58 UTC, SergioEstevao commented
@emilylaguna ready for another round of review.

2024-02-08 00:41 UTC, emilylaguna approved these changes
Nice work. I left one final comment about changing the prompt source from account_details to profile to match Android.

2024-02-08 00:41 UTC, emilylaguna commented on podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
Can we update the accountDetails value to `profile` to match Android?

2024-02-08 09:42 UTC, merged