[Deselecting Chapters] Add feature flag
Automattic/pocket-casts-ios pull request #1397
Opened 2024-02-02 17:27 UTC by leandroalonso

| 📘 Part of: #1396 |
|:---:|

Adds the feature flag for the upcoming deselecting chapters feature.

## To test

1. 🟢 build + code review

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-02-05 19:31 UTC, emilylaguna requested changes
Can we make this a remote feature flag?

2024-02-07 19:36 UTC, leandroalonso commented
@emilylaguna updated! I also did a small change so using remote feature flags are way easier moving forward.

2024-02-13 14:58 UTC, emilylaguna approved these changes
Working for me!

2024-02-13 15:00 UTC, emilylaguna commented on podcasts/AppDelegate.swift
> +        }
I'm not a huge fan of the force unwrapping here, but I don't have a better idea at the moment.

2024-02-13 15:59 UTC, merged