[Slumber] Add in the list of features
Automattic/pocket-casts-ios pull request #1412
Opened 2024-02-05 18:33 UTC by leandroalonso

Adds the Slumber Studios feature to the list of available features in:

1. Upsell screen
2. Prompt screen under account

https://github.com/Automattic/pocket-casts-ios/assets/7040243/008b280d-bf59-47b8-aeb8-219a3e8ae380

## To test

1. Run the app
2. Go to Pofile > Beta Features > make sure `slumber` is toggled ON
3. Login to an account without Plus
4. Go to the "Podcasts" tab
5. Tap the folder locked icon
6. ✅ You should see a mention to Slumber under Plus
7. Tap "Slumber Studios"
8. ✅ Their website should open inside the app. Meaning you won't leave to Safari
9. Dismiss the website and the plus modal
10. Go to Profile > Account
11. ✅ You should a mention to Slumber under Plus
12. Tap "Slumber Studios"
8. ✅ Their website should open inside the app. Meaning you won't leave to Safari
9. Swipe to Patron
10. ✅ You should see the gratitude message (this was added to keep both Plus and Patron of about the same size)
11. Go to Pofile > Beta Features > make sure `slumber` is toggled OFF
12. Re-do the tests, you should not see a mention to Slumber

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-02-05 18:35 UTC, dangermattic commented
<!--
  0 Errors
  2 Warnings: View files have been modified,...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/40">7.57</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-07 04:50 UTC, bjtitus requested changes
✅ upsell screen w/ link
✅ plus carousel w/link
✅ confirmed both with the feature flag off

I left a suggestion about replacing the Regex link finding with `AttributedString` as long as the text is always markdown.

2024-02-07 04:50 UTC, bjtitus commented on podcasts/SwiftUI/UnderlineLinkTextView.swift
> +        }
I think you can replace all of this regex with `AttributedString`'s markdown handling + Runs:

```suggestion
        var attributedString = try! AttributedString(markdown: text)
        attributedString.runs.filter({ $0.link != nil }).forEach({ run in
            attributedString[run.range].underlineStyle = .init(pattern: .solid)
        })

        var textView = Text(attributedString)
```

2024-02-07 14:12 UTC, leandroalonso commented on podcasts/SwiftUI/UnderlineLinkTextView.swift
> +        }
Oh, this is so much better! Thanks!

Done in 72318660a8e1f3debc8000c1c462835cfa6e3177

I did a small change to avoid the force-unwrap.

2024-02-07 16:35 UTC, bjtitus approved these changes
Looks good! Thanks for making the change 🙇

2024-02-07 17:02 UTC, merged