Settings sync: Privacy Flags
Automattic/pocket-casts-ios pull request #1441
Opened 2024-02-15 17:58 UTC by bjtitus

Adds synced settings flag for privacy (crash & log tracking), Marketing Opt-In (Newsletter), and Free Gift Acknowledgement flags.

## To test

### Privacy

1. D1: Navigate to Settings > Privacy
2. D1: Change the "Collect Information" switch
3. D1: Go back to Profile and refresh
4. D2: Refresh the Profile
5. D2: Navigate to Settings > Privacy
6. D2: Check the "Collect Information" switch

### Marketing

1. D1: Navigate to Account
2. D1: Change the "Pocket Casts Newsletter" switch a bit below the fold
3. D1: Go back to Profile and refresh
4. D2: Refresh the Profile
5. D2: Navigate to Account
6. D2: Check the "Pocket Casts Newsletter" switch

### Gift Acknowledgement

This setting doesn't really have any visible effect.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-02-15 18:00 UTC, dangermattic commented
<!--
  0 Errors
  2 Warnings: View files have been modified,...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/41">7.58</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-15 19:46 UTC, leandroalonso requested changes
@bjtitus the project is not building:

<img width="1512" alt="Screenshot 2024-02-15 at 16 45 27" src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/ac8fc358-9f5f-40c0-99c9-71173115d945">

2024-02-15 19:49 UTC, bjtitus commented
@leandroalonso Sorry, just pushed two changes to fix app and unit test compilation.

2024-02-16 16:42 UTC, leandroalonso requested changes
@bjtitus I'm facing the same issue as the shelf PR:

1. I run `trunk`
2. Set Collection information to off (Profile > Privacy)
3. Run this branch with the flag enabled
4. It's turned on

I think you mentioned about doing this part of "carrying" the current option in the future. But I do wonder if that's the best course of action because testing each property will be a lot.

For each property, I think we should:

1. Ensure it's syncing correctly (testing steps already written in the PRs)
2. Ensure when it's updated it reflects the correct behavior
3. Ensure when a user is migrating to this version with the flag disabled that their previous value is still the same
4. Ensure when a user is migrating to this version with the flag enabled that their previous value is still the same

I mention that because one thing that infuriates users is messing with their options/customizations. 😬

Let me know what do you think it's the best way to move forward!

2024-02-16 17:09 UTC, bjtitus commented
@leandroalonso I believe this is due to the import only running a single time after the flag has been enabled. My thought was that no user would need another import once we have completely moved all settings over and that we wouldn't enable this flag until that was complete. Trying to avoid a situation where there's a bug with the flag value and settings are overwritten by their older counterparts.

https://github.com/Automattic/pocket-casts-ios/blob/783c83b140b043f85bab5ae1a5f346646716d6aa/podcasts/AppDelegate%2BDefaults.swift#L129-L134

I do think this behavior can be updated to reset `MigrateToSyncedSettings` when the `settingsSync` flag is _disabled_ so the import has a chance to run again since we don't want a situation where the flag is disabled in production and future.

2024-02-16 17:25 UTC, leandroalonso commented
@bjtitus 

> I believe this is due to the import only running a single time after the feature flag has been enabled. My thought was that no user would need another import once we have completely moved all settings over and that we wouldn't enable this flag until that was complete.

Oh got it! 😌 

>  since we don't want a situation where the flag is disabled in production and settings changes are lost when the settingsSync flag is re-enabled.

This is a very good observation!

> I'll start work on clearing the MigrateToSyncedSettings when the settingsSync flag is disabled if that makes sense to you.

Up to you! I think just adding the context about that on the PRs is enough for now.

2024-02-16 17:30 UTC, bjtitus commented
> I think just adding the context about that on the PRs is enough for now.

Sounds good! I just added an "Import Old Settings" section to be clear about those steps. I'll try to add some more unit tests for these like I did for Player Shelf.

2024-02-19 17:11 UTC, leandroalonso approved these changes
@bjtitus everything worked as expected however I ran into an issue with the "migration":

1. Run the app on D1 with feature flag enabled
2. Set both flags to false
3. Sync
4. Fresh-run the app on D2
5. Keep both flags disabled
6. Enable the feature flag
7. Re-run the app
8. Check that the flags are enabled
9. Sync
10. Go to D1, sync
11. Check that the flags didn't reflect the enabled one

I was able to change the flags only after toggling them twice. Not a blocker but if you can reproduce it worths creating an issue for it.

2024-02-19 17:11 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
>          UserDefaults.standard.set(value, forKey: ServerConstants.UserDefaults.marketingOptInKey)
Is this not under a `else` because this value is what actually opts-in/out for the marketing communication?

2024-02-19 17:16 UTC, bjtitus commented on Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
>          UserDefaults.standard.set(value, forKey: ServerConstants.UserDefaults.marketingOptInKey)
I've been keep all of settings writing outside of the flag. This allows us to disable the flag and not have to migrate from new to old settings, only old to new.

2024-02-19 17:24 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
>          UserDefaults.standard.set(value, forKey: ServerConstants.UserDefaults.marketingOptInKey)
Oh nice!

2024-02-21 05:03 UTC, bjtitus commented
> 5. Keep both flags disabled
> 6. Enable the feature flag
> 7. Re-run the app
> 8. Check that the flags are enabled

In testing, I didn't see any issues with the flags syncing after the FF was enabled. However, I think there is an issue with importing the previous values from `UserDefaults.bool` when it returns `false` for unset keys. There are many values which just default to `false`, but this one is inverting the value so that the `false` value `UserDefaults` returns in the case of `nil` is not correct.

I filed an issue (https://github.com/Automattic/pocket-casts-ios/issues/1461) and will address separately since this affects several other flags.

2024-02-21 05:03 UTC, merged