[Deselect Chapters] Tracks
Automattic/pocket-casts-ios pull request #1462
Opened 2024-02-21 16:57 UTC by leandroalonso

| 📘 Part of: #1396 | Depends #1460 |
|:---:|:---:|

Add tracks.

These are podcasts with chapters you can use to test:

* Clublife: https://pca.st/rLzZCv
* ATP: https://pca.st/accidentaltech

## To test

1. Go to Profile > Settings > Beta Features > `deselectChapters` and `tracksLogging` should be enabled
2. Go to Profile > Settings > Developer > Set to Paid Patron
3. Play any episode with chapters
4. Open the player and go to Chapters
5. Toggle the chapter selection on
6. ✅ `Tracked: deselect_chapters_toggled_on` should be tracked
7. Deselect 3 chapters
8. ✅ `deselect_chapters_chapter_deselected` should be tracked with `podcast_uuid` and `episode_uuid`
9. Tap Done
8. ✅ `Tracked: deselect_chapters_toggled_off ["number_of_deselected_chapters": 3]` should be tracked
10. Toggle chapter selection again
11. Select a chapter that was deselected
12. ✅ `deselect_chapters_chapter_selected` should be tracked with `podcast_uuid` and `episode_uuid`
13. Tap Done
14. ✅ `Tracked: deselect_chapters_toggled_off ["number_of_deselected_chapters": -1]` should be tracked
15. Play the episode
16. ✅  Whenever a chapter is skipped `Tracked: playback_chapter_skipped ["content_type": "audio", "source": "player"]` should be tracked

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-02-22 15:58 UTC, SergioEstevao commented
@leandroalonso  I tested this and all the events are showing up correctly except for the following scenario:

You have chapter 1,2,3.
You deselect 2
Then you start playing on 1
When chapter 1 finishes and the system jumps to 3
I'm not seeing the : `playback_chapter_skipped`
I'm only seeing the above if I press to skip the current chapter

2024-02-22 16:30 UTC, SergioEstevao requested changes
Please check my comment about the skipping chapter event.

2024-02-22 19:26 UTC, leandroalonso commented
@SergioEstevao thanks for spotting that! I have changed the logic in a2c19d86da2c01f85ff68e49c8a8a6646f99d464

Could you please give it another try?

2024-02-23 12:36 UTC, SergioEstevao approved these changes
Skipping chapter event is now showing up! :shipit:

2024-02-23 13:55 UTC, merged