Settings Sync: Remove unused shouldUseNewSettingsSync param
Automattic/pocket-casts-ios pull request #1506
Opened 2024-03-13 03:35 UTC by bjtitus

Cleans up an unused `shouldUseNewSettingsSync` on `SyncManager` and `SyncSettingsTask`.

## To test

* Make sure CI compiles 🟢 
* Test that settings syncing works:
    * Install on two devices/simulators
    * Enable the `settingsSync` feature flag
    * Restart the app
    * Make sure that changing settings on one and refreshing shows the same setting on the other

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-03-13 16:03 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/43">7.60</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-03-13 17:58 UTC, leandroalonso requested changes
@bjtitus shouldn't this also sync the settings once the flag is enabled? I just the following test:

1. Run a clean install
2. Create a fresh new account
3. Change some settings (I changed Appearance)
4. Enable `syncSettings`
5. Sync
6. Everything gets reverted

2024-03-13 18:29 UTC, bjtitus commented
@leandroalonso Sorry, I may have needed to apply https://github.com/Automattic/pocket-casts-ios/pull/1507 before this really works properly. I just merged those changes and it seems to be working to me when doing the following:

1. Deleted the app and logged in to the same account on the two devices
2. Enabled `newSettingsStorage` flag on both devices
3. Restart the app on both devices - settings should still be migrated over at this point and won't need another migration after this flag is enabled
4. D1: Change some settings
5. D1: Enable `settingsSync`
6. D1: Refresh
7. D2: Change some settings
8. D2: Enable `settingsSync`
9. D2: Refresh
10. The settings should be merged across D1 & D2 depending on the time they were changed

2024-03-14 18:36 UTC, leandroalonso approved these changes
@bjtitus I'm still experiencing the same as [mentioned here](https://github.com/Automattic/pocket-casts-ios/pull/1506#pullrequestreview-1934859498).

Basically, when I already have some settings set and toggle `newSettingsStorage` and `settingsSync` on and go to Profile > Refresh Now, everything is gone.

I guess this has to do with the app not restarting thus the migration never happens. We will add some logic when remotely toggling the flag on/off?

Anyway, this is not related to this PR.

2024-03-14 20:30 UTC, bjtitus commented
@leandroalonso Ah yes, this is being handled here but not when flags are overridden manually:

https://github.com/Automattic/pocket-casts-ios/blob/12400265f71dc744e85275f9cf093ffb3a70cf8e/podcasts/AppDelegate.swift#L315-L320.

I'm wondering if we should call `updateRemoteFeatureFlags` any time these flags are changed locally but we should chat about that.

2024-03-14 23:11 UTC, merged