Categories: Pills styling
Automattic/pocket-casts-ios pull request #1611
Opened 2024-04-10 04:10 UTC by bjtitus

Tweaks a few colors and padding for Category Pills

* The background of the Category pills matches the search bar background
* Various color changes to the pill backgrounds, selected, and pressed colors

|  |  |  |
|---|---|---|
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 33](https://github.com/Automattic/pocket-casts-ios/assets/3250/6805120a-c3ac-4b1d-a023-cebafe5b7fb1) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 38](https://github.com/Automattic/pocket-casts-ios/assets/3250/4a4f9d56-b2fc-4d5c-b2fb-14e49fec83c1) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 42](https://github.com/Automattic/pocket-casts-ios/assets/3250/1e71ed81-97f3-49d3-a26e-c747525c51a8) |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 29](https://github.com/Automattic/pocket-casts-ios/assets/3250/2af874aa-1255-42f3-9057-be07e17f1b05) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 48](https://github.com/Automattic/pocket-casts-ios/assets/3250/8a27d8e1-103e-456a-a113-5b9324321be4) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 54](https://github.com/Automattic/pocket-casts-ios/assets/3250/0c091617-484e-492d-a2c3-bf719acba342) |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 45 00](https://github.com/Automattic/pocket-casts-ios/assets/3250/34a51ae5-9c31-4dd5-9a1c-f19c6d1804e2) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 23](https://github.com/Automattic/pocket-casts-ios/assets/3250/c433b269-218a-4a1b-af90-c715a10a5b27) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 16](https://github.com/Automattic/pocket-casts-ios/assets/3250/d875a2ee-89b8-4cd8-99fb-02525100a2f6) |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 21 44 11](https://github.com/Automattic/pocket-casts-ios/assets/3250/8c77bcd1-0db9-44cc-b7a3-668fb1f0f142) |  |

## To test

* Build for Staging
* Enable the `categoriesRedesign` feature flag
* Navigate to Discover
* Ensure that the Category pills appear and are interactive
* Change themes
* Ensure that the Category pills reflect the current theme and appear to have the correct styling

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-04-10 04:10 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-04-12 16:20 UTC, leandroalonso requested changes
@bjtitus in the classic theme the pill "disappears" when selected:

<img src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/718c405d-c8fd-4c28-9aa7-2eb2537d51de" width="300">

--

[nit] Not necessarily need to be done but I see that the "loading indicator" seems not well aligned:

https://github.com/Automattic/pocket-casts-ios/assets/7040243/c1078bdf-7fab-420a-88e5-dbdf64670eef

2024-04-15 03:01 UTC, bjtitus commented
@leandroalonso This should be settled now and I went ahead and checked in the Previews.

2024-04-15 03:03 UTC, bjtitus commented
Here are the colors I selected; I've annotated them in place in screenshots to avoid confusion @mebarbosa.

@david-gonzalez-a8c, could you give these a once over and see if they make sense? There is still a known issue with the close button not being a true circle which I'll fix later on so please ignore that.

| Unselected | Pressed | Selected |
| -- | -- | -- |
| <img src="https://github.com/Automattic/pocket-casts-ios/assets/3250/ace1a27c-8776-4f9b-8ab6-d871faa60047" width=200> | <img src="https://github.com/Automattic/pocket-casts-ios/assets/3250/bd0b1102-e3cc-4167-b120-d10e740d72c4" width=200> | <img src="https://github.com/Automattic/pocket-casts-ios/assets/3250/f26b45f6-25c9-410a-a1e8-d600e86422ed" width=200> |

2024-04-15 14:41 UTC, leandroalonso approved these changes

2024-04-15 16:24 UTC, david-gonzalez-a8c commented
These look good to me.

The semantics of the color variables are still a bit confusing to me, and my bad for using different ones in the specs. But maybe $primary-field-03 is a better candidate for the border color instead of $primary-icon-02, and $primary-interactive-01 for the background color of the selected state instead of $secondary-icon-01

2024-04-15 20:24 UTC, bjtitus commented
@david-gonzalez-a8c Unfortunately, the `primary-interactive-01` color seems to have the same issue as the original color I was using so I'll keep `secondary-icon-01` for now.

| secondary-icon-01 | primary-interactive-01 |
|--|--|
| ![Old](https://github.com/Automattic/pocket-casts-ios/assets/3250/f26b45f6-25c9-410a-a1e8-d600e86422ed) | ![CleanShot 2024-04-15 at 14 18 01@2x](https://github.com/Automattic/pocket-casts-ios/assets/3250/de48343d-a374-491e-aa92-3f3ab794890a) |

2024-04-15 20:46 UTC, merged