Override userInterfaceStyle so it matches PC's Theme type to ensure iOS's Increase Contrast setting does the right thing
Automattic/pocket-casts-ios pull request #1637
Opened 2024-04-22 18:00 UTC by bikrrr

Set the `tabBar`'s `userInterfaceStyle` to match Pocket Casts' Theme type so iOS's **Increase Contrast** setting always increases icon contrast.

## Problem
When a _single_ Pocket Cast theme is selected and doesn't change based on iOS light/dark mode, the iOS **Accessibility › Display & Text Size › Increase Contrast** setting won't always increase the contrast of the tabBar icons. If the PC theme is light and the iOS theme is dark, the icons will actually get lighter instead of darker. The same is true for light/dark are reversed.

Here's a summary of the different combinations. Notice the **increase contrast** cells aren't correct (❌) when the Pocket Casts theme is _opposite_ the iOS appearance.

| iOS Appearance/Contrast| Pocket Cast "Default Light" | "Default Dark" |
|--------|--------|--------|
| Light/Normal | ![Screenshot 2024-04-22 at 11 24 24@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/ab2c87b6-207d-4cdf-8e30-ad50b0dc28ae) | ![Screenshot 2024-04-22 at 11 25 23@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/28a33ea3-477a-4f65-916d-2dd907b97714) |
| Light/Increase | ✅![Screenshot 2024-04-22 at 11 24 37@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/91058898-1eef-4305-b5f6-7a528746a76a) | ❌ ![Screenshot 2024-04-22 at 11 25 35@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/858b5158-870d-4e92-b6fd-4cd71a4851c4) |
| Dark/Normal | ![Screenshot 2024-04-22 at 11 24 10@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/95855cfb-eed5-46fc-93b0-7cb5a9b07331) | ![Screenshot 2024-04-22 at 11 25 49@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/bf9c8f0b-1093-4708-a27b-babf9d0f8ae5) |
| Dark/Increase | ❌ ![Screenshot 2024-04-22 at 11 23 07@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/7b5ab71d-216a-4cb1-a65f-459e6553a721) | ✅ ![Screenshot 2024-04-22 at 11 26 45@2x](https://github.com/Automattic/pocket-casts-ios/assets/2607653/7d901e29-5480-4870-974f-d9dba0b832a6) |

**Video of Issue**

https://github.com/Automattic/pocket-casts-ios/assets/2607653/1e23403a-a77e-45c2-a62c-99d7c0ec8926

## Fix
This fix sets the overrideUserInterfaceStyle so it matches the PC theme. When **Increase Contrast** is enabled, it always makes it darker with a light theme and lighter with a dark theme, regardless of whether iOS is dark or light (since the background color isn't changing with iOS).

**Video of Fix**

https://github.com/Automattic/pocket-casts-ios/assets/2607653/1fd9f4f7-7a99-4e77-9e59-d45631162184

## To test

### Single Pocket Casts Theme

1. **Pocket Casts › Settings › Appearance**, turn off **Use iOS Light/Dark Mode**
2. Select **Default Light** theme
3. Set iOS **Appearance** to **Light**
4. Toggle on/off iOS **Settings › Accessibility › Display & Text Size › Increase Contrast** (simulator menu **Features › Toggle Increased Contrast**)
5. ✅ Confirm the tab bar icons get _darker_ when **Increase Contrast** is on.
6. Set iOS **Appearance** to **Dark**
7. Toggle on/off iOS **Settings › Accessibility › Display & Text Size › Increase Contrast** (simulator menu **Features › Toggle Increased Contrast**)
8. ✅ Confirm the tab bar icons get _darker_ when **Increase Contrast** is on.

### Separate Pocket Casts Themes for iOS Light/Dark mode
1. **Pocket Casts › Settings › Appearance**, turn on **Use iOS Light/Dark Mode**
2. For **Light Theme**, select **Default Light**
3. For **Dark Theme**, select **Default Dark**
4. Set iOS **Appearance** to **Light**
5. Toggle on/off iOS **Settings › Accessibility › Display & Text Size › Increase Contrast** (simulator menu **Features › Toggle Increased Contrast**)
6. ✅ Confirm the tab bar icons get _darker_ when **Increase Contrast** is on.
7. Set iOS **Appearance** to **Dark**
8. Toggle on/off iOS **Settings › Accessibility › Display & Text Size › Increase Contrast** (simulator menu **Features › Toggle Increased Contrast**)
9. ✅ Confirm the tab bar icons get _lighter_ when **Increase Contrast** is on.
## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-04-22 18:19 UTC, bikrrr commented
I first noticed a similar problem with badge backgrounds and had a fix all lined up, but then saw that there's a podcast tiles screen redesign in the works. So, I just tackled the tab bar first since that's still a problem in that fork.  

I have a similar fix for the 'updateNavColors()` method in `PCNavigationController.swift`, but I'm very new at this and wanted to submit this independently to see how it goes!? 😅

2024-04-23 14:24 UTC, leandroalonso requested changes
Nice work and awesome detailed description!

It works as intended. Left just a few comments about minor changes and fixing a warning (lint issue).

2024-04-23 14:24 UTC, leandroalonso commented on podcasts/MainTabBarController.swift
> +
```suggestion

```

There's a warning here due to the empty space.

2024-04-23 14:24 UTC, leandroalonso commented on podcasts/MainTabBarController.swift
> +        tabBar.overrideUserInterfaceStyle = isDarkTheme ? .dark : .light
I believe we can rewrite that in a single line while keeping the readability:

```suggestion
        tabBar.overrideUserInterfaceStyle = Theme.isDarkTheme() ? .dark : .light
```

2024-04-23 14:35 UTC, bikrrr commented on podcasts/MainTabBarController.swift
> +        tabBar.overrideUserInterfaceStyle = isDarkTheme ? .dark : .light
Yes, good call. That's a remnant of more complicated code I had tried. I should have removed it since I ended up with the single ternary. Thanks!

2024-04-24 14:05 UTC, merged

2024-04-24 14:05 UTC, leandroalonso commented
Thanks for your contribution @bikrrr! Merged!