Reimagine Sharing: Add new Modal with sharing options
Automattic/pocket-casts-ios pull request #1650
Opened 2024-04-24 17:35 UTC by bjtitus

* Adds new styled modal when sharing from Now Playing to select Podcast, Episode, or Current Position
* Adds new ModalView which will contain different assets and sharing options

## To test

Steps to test your PR.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-04-29 17:34 UTC, SergioEstevao commented on podcasts/NowPlayingPlayerItemViewController+Shelf.swift
> +            SharingModal.showModal(episode: episode, in: self)
Why not return immediately here instead of doing an else?

2024-04-29 17:39 UTC, SergioEstevao commented on podcasts/SharingHelper.swift
> +            SharingModal.show(option: .podcast, podcast: podcast, episode: nil, in: fromController)
Why not return immediately here instead of doing an else?

2024-04-29 17:40 UTC, SergioEstevao requested changes
Working correctly, just left some suggestions for code improvements.

2024-05-10 03:41 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/47">7.64</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-05-13 22:08 UTC, bjtitus commented
@SergioEstevao This is ready for review again!

2024-05-14 13:15 UTC, SergioEstevao approved these changes
Looking good. :shipit:

2024-06-18 19:38 UTC, merged