Fix 1686 grid margins go off screen
Automattic/pocket-casts-ios pull request #1687
Opened 2024-05-02 09:49 UTC by SergioEstevao

Fixes #1686 

This PR updates the search bar code and mini-player code to ensure it does not change any existing horizontal insets when updating the insets.

## To test

 - Start the app
 - On podcasts view pull to refresh, and while the pull to refresh is ongoing pull to refresh again.
 - Check that the horizontal margins on the grid layout are kept
 - Start the playing any podcast to see the mini-player
 - Check if you have a bottom margin at the end of scroll the podcasts view
 - Tap on the mini-player artwork and choose `Close and Clear Up Next`
 - Check that the bottom at the end of the scroll is still there and horizontal margins are kept

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-05-02 09:50 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/46">7.63 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-05-10 14:29 UTC, leandroalonso requested changes
This needs to target `trunk`.

2024-05-10 18:11 UTC, leandroalonso requested changes
@SergioEstevao I don't believe `trunk` has the grid changes applied. We probably need to re-add them, merge them first, and then update this PR.

2024-05-10 18:17 UTC, SergioEstevao commented
I will pull the other one before, because this fix only makes sense when you have horizontal margins to test.

2024-05-13 22:26 UTC, SergioEstevao commented
@leandroalonso ready for another look now that we re-added the new grid layout to trunk.

2024-05-14 15:02 UTC, SergioEstevao commented on podcasts/SceneHelper.swift
> +            let rootVC = appScene?.rootViewController
These changes were not part of this PR, I think this comes from another PR that is still not merged in trunk.

2024-05-14 15:03 UTC, leandroalonso commented on podcasts/SceneHelper.swift
> +            let rootVC = appScene?.rootViewController
Just a `merge trunk` missing. :)

Gone already.

2024-05-14 15:04 UTC, leandroalonso approved these changes

2024-05-14 15:14 UTC, merged