New grid layout improvements
Automattic/pocket-casts-ios pull request #1760
Opened 2024-05-15 15:04 UTC by SergioEstevao

Fixes #1689 #1690

This address some UI issue that were found on the new grid layout

- It increases the size of the unplayed episodes badge
- It correct the background color of the badge to match the collection background
- It adds a shadow around the podcast image to create contrast with the background and some depth

https://github.com/Automattic/pocket-casts-ios/assets/651601/63516ec1-09ef-42cb-8ec7-e8bb272ea6ed

## To test

- Start the app
- Go to Podcasts tab
- Activate the grid layout by tapping on the top right more button and choose a grid layout
- Activate badges for unplayed episodes
- Check if all is looking correct
- Change a different grid layout
- Check if still shows correctly
- Change to a different type of badges
- Check if all looks correct
- Disable badges
- Check if it looks correct

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-05-15 15:05 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/47">7.64 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-05-16 15:16 UTC, bjtitus requested changes
Just a few minor changes. Things looked good in testing 👍

2024-05-16 15:16 UTC, bjtitus commented on podcasts/PodcastGridCell.swift
> +        shadowView.layer.shadowPath = UIBezierPath(rect: bounds).cgPath
Shouldn't `super.layoutSubviews()` be called here?

2024-05-16 15:16 UTC, bjtitus commented on podcasts/GridBadgeView.swift
> +            simpleBadge.heightAnchor.constraint(equalToConstant: 15),// The total siize needs to take account the border witdth too
Small typos here:
```suggestion
            simpleBadge.heightAnchor.constraint(equalToConstant: 15),// The total size needs to take account the border width too
```

2024-05-16 17:30 UTC, SergioEstevao commented
@bjtitus I addressed your review comments and added shadows to the folder cells too.

2024-05-16 17:47 UTC, bjtitus approved these changes
:shipit: Looks good!

2024-05-16 18:37 UTC, merged