Download Issues: Cancel URLSession tasks when deleting unused podcasts
Automattic/pocket-casts-ios pull request #1785
Opened 2024-05-28 02:04 UTC by bjtitus

We clear out unused podcasts after a refresh but do not touch the scheduled URLSession tasks. This could lead to out of date tasks which are no longer needed.

## To test

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-05-28 02:05 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-05-28 14:22 UTC, leandroalonso submitted a review, later dismissed
@bjtitus can we put this new logic behind the same feature flag we used in the other PR?

I know it all seems pretty straightforward and you added tests to ensure the behavior but we don't know what we don't know. 😇 

Ideally we should be able to restore the previous logic in case anything goes wrong.

2024-05-28 14:22 UTC, leandroalonso commented on PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
> +    override func parentPodcast(dataManager: DataManager) -> Podcast? {
We added `dataManager` as an argument but it's not used inside the function. Did I miss anything?

2024-05-28 14:22 UTC, leandroalonso commented on PocketCastsTests/Tests/Utilities/PodcastManagerTests.swift
> +        XCTAssertEqual(dataManager.findEpisode(uuid: episode.uuid), episode)
Isn't that kinda of a test to make sure the Mock Data Manager works? Do we need to test that here? Wouldn't the rest of the asserts fail in case this doesn't work?

2024-05-28 14:55 UTC, bjtitus commented on PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
> +    override func parentPodcast(dataManager: DataManager) -> Podcast? {
I don't think it needs to be used here since it's a mock. It was required to override the [changed method in Episode](https://github.com/Automattic/pocket-casts-ios/pull/1785/files#diff-6e22a3f4b4630aa41269a0e49fa7dc254f04226db8056e7cef087237074128feR166).

2024-05-28 15:00 UTC, bjtitus commented
> can we put this new logic behind the same feature flag we used in the other PR

Absolutely! I did this locally but must have lost it in cherry picking somewhere. It's added in https://github.com/Automattic/pocket-casts-ios/pull/1785/commits/40a91ed4c0253ca34713e35396a21f7b6a17d2d5 but only covers the task cancellation. I _could_ see the async changes causing issues but I think I'd need to duplicate the methods to do that properly. I think it's sufficient to flag only the task cancellation bit if we test the Podcast view controller thoroughly, but what do you think?

2024-05-28 15:04 UTC, bjtitus commented on PocketCastsTests/Tests/Utilities/PodcastManagerTests.swift
> +        XCTAssertEqual(dataManager.findEpisode(uuid: episode.uuid), episode)
Yeah, it is, although this isn't the `DataManagerMock`, but a full separate test database instance.

I wondered if this is covering too much but when I was writing the test, any mismatch in the sample podcast or episode would cause the episode or podcast not to exist (failed database save, which is just logged to the console). In that case, the assertion to check for a running task would probably catch it but it didn't seem very clear.

I could also, or instead of these assertions, add a check that the first task is for the URL we expect, which would at least cover the case where some other tasks sneaks in.
```swift
XCTAssertEqual(task.originalRequest?.url?.absoluteString, episode.downloadUrl)
```

2024-05-28 20:55 UTC, leandroalonso commented
> I think it's sufficient to flag only the task cancellation bit if we test the Podcast view controller thoroughly, but what do you think?

Up to you!

One last question, would be possible to test the task cancelation? Like forcing a specific podcast to be deleted or something like that?

@SergioEstevao I'm sharing my 2 cents here and there but feel free to review it as you were the original reviewer.

2024-05-28 21:30 UTC, SergioEstevao commented
@bjtitus do we really need this to go in 7.65? Can't it go to trunk?

2024-05-28 21:40 UTC, SergioEstevao requested changes
Great work in this feature, and replacing all the the use of direct singletons for instance classes.
Code wise is also looking good, just wanted to be sure that we want this on 7.65?

2024-05-29 14:15 UTC, leandroalonso commented
> Code wise is also looking good, just wanted to be sure that we want this on 7.65?

We're somewhat fine having that on 7.65 IMHO as we still have 1 and a half week of testing time. But from now on we should definitely target `trunk`.

2024-05-29 22:11 UTC, bjtitus commented
@leandroalonso I've updated with another test with a script to rewrite the database. I left some comments in the script to try and explain but it's essentially setting up a podcast which a user may have unsubscribed from or only ever visited in Discover and then downloaded podcasts directly from there. I could see an argument about whether these episodes should be deleted, but we should at least cancel any download tasks since they are _currently_ being deleted from the database and will be orphaned.

2024-05-29 22:12 UTC, bjtitus commented
@SergioEstevao + @leandroalonso I bumped this to 7.66 at this point since it's several days into the next release.

2024-05-30 07:54 UTC, SergioEstevao approved these changes
:shipit:

2024-05-31 16:08 UTC, merged