Make prototype build conditional and split build from upload steps
Automattic/pocket-casts-ios pull request #1808
Opened 2024-06-06 04:30 UTC by mokagio

Makes local builds faster.Fixes #

Please include a summary of the changes and the related issue.

## To test

Steps to test your PR.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
Makes local builds faster.

2024-06-06 04:31 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-06-06 14:44 UTC, leandroalonso requested changes

2024-06-06 14:44 UTC, leandroalonso commented on .buildkite/commands/prototype-upload.sh
> +bundle exec fastlane upload_entreprise
Typo:

```suggestion
bundle exec fastlane upload_enterprise
```

2024-06-06 14:44 UTC, leandroalonso commented on fastlane/Fastfile
>    lane :build_and_upload_entreprise do
```suggestion
  lane :build_and_upload_enterprise do
```

2024-06-11 00:26 UTC, mokagio commented on .buildkite/commands/prototype-upload.sh
> +bundle exec fastlane upload_entreprise
Ah! Thanks @leandroalonso !

2024-06-11 00:39 UTC, pocketcasts commented
<!-- REUSE_ID: prototype-build-link-pocket-casts --><details><summary><img alt='Pocket Casts Prototype Build' align='top' src='https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/d8cac792-0c9e-46e9-880a-a71037efda92/AppIcon60x60%402x.png?sv=2019-02-02&sr=c&sig=egLhn8RgzIbQAKLQU3Ynm%2BWO%2FsIeFSVdvRRT%2FOc5syM%3D&se=2024-06-18T00%3A39%3A42Z&sp=r' width='20px' />📲 You can test the changes from this Pull Request in <b>Pocket Casts Prototype Build</b> by scanning the QR code below to install the corresponding build.</summary>
<table>
<tr>
  <td rowspan='6' width='260px'><img src='https://api.qrserver.com/v1/create-qr-code/?size=500x500&qzone=4&data=https%3A%2F%2Finstall.appcenter.ms%2Forgs%2Fautomattic%2Fapps%2FPocket-Casts-Prototype-Builds%2Freleases%2F11' width='250' height='250' /></td>
  <td><b>App Name</b></td><td><img alt='Pocket Casts Prototype Build' align='top' src='https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/d8cac792-0c9e-46e9-880a-a71037efda92/AppIcon60x60%402x.png?sv=2019-02-02&sr=c&sig=egLhn8RgzIbQAKLQU3Ynm%2BWO%2FsIeFSVdvRRT%2FOc5syM%3D&se=2024-06-18T00%3A39%3A42Z&sp=r' width='20px' /> Pocket Casts Prototype Build</td>
</tr>
<tr><td><b>Build Number</b></td><td>pr1808-510d606</td></tr>
<tr><td><b>Version</b></td><td>7.65</td></tr>
<tr><td><b>Bundle ID</b></td><td>au.com.shiftyjelly.podcasts.prototype</td></tr>
<tr><td><b>Commit</b></td><td>510d606e04d06de8b19f611f18f32e8e57d022a7</td></tr>
<tr><td><b>App Center Build</b></td><td><a href='https://install.appcenter.ms/orgs/automattic/apps/Pocket-Casts-Prototype-Builds/releases/11'>Pocket Casts - Prototype Builds #11</a></td></tr>
</table>
<em>Automatticians: You can use our internal self-serve MC tool to give yourself access to App Center if needed.</em>
</details>

2024-06-11 14:25 UTC, leandroalonso approved these changes
:shipit: 

@mokagio one question: shouldn't we make the `Prototype Build - Build` and `Prototype Build - Upload` checks to be optional? They won't run for all PRs but they shouldn't also block a merge.

2024-06-11 22:03 UTC, mokagio commented
>  shouldn't we make the Prototype Build - Build and Prototype Build - Upload checks to be optional? They won't run for all PRs but they shouldn't also block a merge.

@leandroalonso that should be the case already. I'm going to merge this into its base, see what GitHub shows in the checks, and update as necessary.

2024-06-11 22:04 UTC, merged

2024-06-11 22:07 UTC, mokagio commented
> I'm going to merge this into its base, see what GitHub shows in the checks, and update as necessary.

Looking good so far:

![image](https://github.com/Automattic/pocket-casts-ios/assets/1218433/aa175468-27a6-418d-aa17-150ebf00db55)

I think that the required `buildkite/pocket-casts-ios` step (the whole pipeline) should report as completed because of how the Prototype Build block step is configured: by [default](https://buildkite.com/docs/pipelines/block-step#block-step-attributes) `blocked_state` is `passed`. 

We'll see in a few minutes once the build finishes.

2024-06-12 14:28 UTC, leandroalonso commented
@mokagio amazing! Thank you!