Update settingsHelpShown -> settingsGetSupport event
Automattic/pocket-casts-ios pull request #1857
Opened 2024-06-24 21:09 UTC by bjtitus

The `settings_get_support` event matches the Android version.

## To test

* Enable `tracksLogging` in Beta Features
* Navigate to Profile
* Tap `Help & Feedback` cell
* Verify that the following is logged:
```
🔵 Tracked: settings_get_support
```

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-06-24 21:09 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: PR is not assigned to a milest...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-06-25 11:13 UTC, SergioEstevao approved these changes
:shipit:

2024-06-25 14:31 UTC, leandroalonso requested changes
@bjtitus I believe this rename is incorrect.

The `settingsHelpShown` also exists on Android. What we don't have is the events when you tap "Leave Feedback" and "Get Support" from within the view that opens:

<img width="300" alt="Screenshot 2024-06-25 at 11 29 08" src="https://github.com/Automattic/pocket-casts-ios/assets/7040243/4f0ceaca-14a5-4226-a6bd-56481d97a361">

Here's a recording showing how to show this:

https://github.com/Automattic/pocket-casts-ios/assets/7040243/25a97cf8-559a-485e-8a8f-2203f752678b

2024-06-25 16:54 UTC, bjtitus commented
@leandroalonso Sorry, my mistake. It looks like we were logging similar ones to Firebase already so I added the Tracks versions (`settings_leave_feedback` and `settings_get_support`) in this PR: https://github.com/Automattic/pocket-casts-ios/pull/1861

2024-06-25 16:54 UTC, closed without merging