Transcripts: add player transition to Transcripts
Automattic/pocket-casts-ios pull request #1899
Opened 2024-07-10 18:15 UTC by leandroalonso

Fixes #

Please include a summary of the changes and the related issue.

## To test

Steps to test your PR.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-07-11 16:30 UTC, bjtitus requested changes
👏 Looks really good in testing! 💅

I left just a few pieces of code feedback.

2024-07-11 16:30 UTC, bjtitus commented on podcasts/NowPlayingPlayerItemViewController.swift
> +        UIView.animate(withDuration: 0.35, animations: { [weak self] in
🔧 I feel like the sequence of events here is very similar in the two animations. Would it make sense to combine them into a single animation and set the values based on an `isShowing` property? Is that overthinking it? I guess I'm more worried that something would be missing from one side of the animation so this would make it less likely.

```swift
UIView.animate(withDuration: 0.35, animations: { [weak self] in
	guard let self else { return }
	
	shelfBg.isHidden = !isShowing
	shelfBg.layer.opacity = isShowing ? 1 : 0
	
	transcriptContainerView.isHidden = isShowing
	transcriptContainerView.layer.opacity = isShowing ? 0 : 1
	
	bottomControlsStackView.distribution = isShowing ? .equalSpacing : .fill
	bottomControlsStackView.spacing = isShowing ? 30 : 10
	
	fillView.isHidden = isShowing
	
	let skipButtonSize: SkipButtonSize = isShowing ? .large : .small
	skipBackBtn.changeSize(to: skipButtonSize)
	skipFwdBtn.changeSize(to: skipButtonSize)
	skipBackBtn.layoutIfNeeded()
	skipFwdBtn.layoutIfNeeded()
	
	if isShowing {
		playerContainer?.showTabsAndUnlockScrollView()
	} else {
		playerContainer?.hideTabsAndLockScrollView()
	}
}, completion: { [weak self] _ in
	guard let self else { return }
	
	if isShowing {
		transcriptContainerView.isHidden = true
	}
	
	playPauseBtn.finishedTransition()
	skipBackBtn.finishedTransition()
	skipFwdBtn.finishedTransition()
})
```

2024-07-11 16:30 UTC, bjtitus commented on podcasts/SkipButton.swift
> +
I think there's an extra space here
```suggestion

```

2024-07-11 16:30 UTC, bjtitus commented on podcasts/PlayPauseButton.swift
> +    func prepareForAnimateTransition(withBackground: UIColor?) {
❓ I don't think the `withBackground` color is used here, can it be removed?

2024-07-11 16:30 UTC, bjtitus commented on podcasts/PlayerContainerViewController.swift
> +    }
🤔 Would it make sense to combine these or is that less clear?

```suggestion
    func updateTabsAndUnlockScrollView(isEnabled: Bool) {
            mainScrollView.isScrollEnabled = isEnabled
            topSpaceToHeader.isActive = isEnabled
            topSpaceToSafeArea.isActive = !isEnabled
            view.layoutIfNeeded()
    }
```

2024-07-11 18:41 UTC, leandroalonso commented on podcasts/NowPlayingPlayerItemViewController.swift
> +        UIView.animate(withDuration: 0.35, animations: { [weak self] in
Done in 3328b3f34b1aa9d76be6a34ae9e4de666bed1dfd

2024-07-11 18:42 UTC, leandroalonso commented on podcasts/PlayPauseButton.swift
> +    func prepareForAnimateTransition(withBackground: UIColor?) {
Done in f1553062043db5be7db1c89f49a4dc411b17990d

2024-07-11 18:42 UTC, leandroalonso commented on podcasts/PlayerContainerViewController.swift
> +    }
Done in debf21cc39ffaf78438d7e377ef658ebccbcbb6a

2024-07-11 18:42 UTC, leandroalonso commented
@bjtitus thanks for the suggestions! Ready for another look!

2024-07-12 01:43 UTC, bjtitus approved these changes
:shipit: Looks good! 🙇

2024-07-12 13:22 UTC, merged