Reimagine Sharing: Clip playback
Automattic/pocket-casts-ios pull request #1947
Opened 2024-07-26 00:17 UTC by bjtitus

| 📘 Part of: #1910 |
|:---:|

Adds clip playback via a new `ClipPlaybackManager` which uses a separate `AVPlayer` instance.

## To test

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-07-26 00:17 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-26 13:45 UTC, leandroalonso requested changes
@bjtitus tested and it works as described, there are a few things worth mentioning:

1. When tapping play and closing the screen, playback don't stop. We need to ensure that leaving the screen stops the playback;
2. The playhead can be out of bounds with the trimmer: is that expected? Taking as an example the Photos app: the playhead is always contained inside the trimmer bounds.
3. I wonder if we should follow the Photos behavior: when moving the trimmer, any playback stops and the playhead disappears. After the trimming is done, the playhead re-appears at the beginning of the trimmed part. This should also fix the "Trim handles are slightly sluggish during playback, especially on older devices" known issue
4. When moving the playhead for a streaming episode it moves back to the previous position while the seek is being performed (it would be better to stay at the moved position)

None of those are blockers except (1)

2024-07-26 13:45 UTC, leandroalonso commented on podcasts/Sharing/Clip/ClipPlaybackManager.swift
> +        PlaybackManager.shared.pause()
Shall we inject this?

2024-07-26 16:15 UTC, bjtitus commented
**1**

> When tapping play and closing the screen, playback don't stop

✅ Fixed

**2**
> The playhead can be out of bounds with the trimmer

Yep, I have code for this but just haven't pushed it yet. I'll do that as a separate PR.

**3**
> I wonder if we should follow the Photos behavior: when moving the trimmer, any playback stops and the playhead disappears.

This is an interesting idea. I'll take a look at this alongside 2.

**4**
> When moving the playhead for a streaming episode it moves back to the previous position while the seek is being performed

Are you talking about the quick jump? I was looking a bit and I think I will have to delay the update while seek is happening.

https://github.com/user-attachments/assets/1e5fa956-64d9-4eaf-b90e-6a8b82055a84

2024-07-26 19:22 UTC, bjtitus commented
@leandroalonso I added the seek ignoring logic for number 4 in https://github.com/Automattic/pocket-casts-ios/pull/1947/commits/601a27fa230d88ef3124b69a4f372b78dbcc7500

2024-07-29 14:55 UTC, leandroalonso approved these changes
✅ Tested closing the screen while playback is ongoing
✅ Tested moving the playhead while streaming

2024-08-07 16:36 UTC, merged