Add logging to PlaybackManager
Automattic/pocket-casts-ios pull request #2016
Opened 2024-08-09 13:21 UTC by bjtitus

We have some reports of playback resuming on its own without user intervention. It seems these _may_ be caused by audio interruptions from the system so we should improve logging for these. This may also help debug CarPlay issues where audio doesn't resume after directions are read.

Adds the following to logs:
- "PlaybackManager Play" log to track when Play is called. This is the equivalent to the "pausing playback" log
- Episode title to "pausing playback" log
- `AVAudioSession.InterruptionReason` to the "PlaybackManager handleAudioInterrupt" began + ended logs so we can determine why an audio session was interrupted or restarted

## To test

* Play and pause a podcast
* Verify you see the following logs:
```
PlaybackManager Play <Episode Title> userInitiated: <true/false>
```

```
PlaybackManager pausing playback <Episode Title>
```

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-08-09 13:21 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  1 Warning: PR is not assigned to a milest...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-12 16:10 UTC, leandroalonso requested changes
@bjtitus I tested the interruptionReason and it seems not much info is given and it caused a crash:

<img width="1513" alt="Screenshot 2024-08-12 at 13 09 56" src="https://github.com/user-attachments/assets/3048e0b9-a2e2-4719-ae76-c05ee9716046">

All I did was to call my own phone.

2024-08-12 16:32 UTC, bjtitus commented
It looks like the `ended` audio interruption type typically doesn't have a reason. I removed the force unwrap for that and I'm seeing "unknown" for those in testing.

The reason is mostly to differentiate the audio route changes from other system audio takeover. I think it'll prove useful for users who may be disconnecting from CarPlay, HomePods, or AirPods.

The first is a Siri invocation here and the second is AirPods disconnecting:

```
PlaybackManager handleAudioInterrupt began reason: 0
PlaybackManager handleAudioInterrupt ended, should attempt to restart audio: 1 reason: unknown
PlaybackManager handleAudioInterrupt began reason: 4
PlaybackManager handleAudioInterrupt began reason: 4
```

2024-08-12 16:49 UTC, leandroalonso approved these changes

2024-08-12 16:54 UTC, leandroalonso commented
@bjtitus I believe you need to put macros to exclude your changes from watchOS.

2024-08-12 17:05 UTC, merged