Reimagine Sharing: Export audio clips
Automattic/pocket-casts-ios pull request #2044
Opened 2024-08-15 20:07 UTC by bjtitus

| 📘 Part of: #1910  |
|:---:|

Adds exporting of audio only clips:

## To test

* Play an episode
* Tap on the "Share" button in the action shelf
* Tap on "Clip" from the share modal
* Create a clip and swipe over the the audio symbol
* Tap "Clip"
* Tap the "More" share option and share or save to a file
* Verify that an `m4a` audio file is shared

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-08-15 20:08 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  2 Warnings: View files have been modified,...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-16 11:12 UTC, danielebogo requested changes
Hey @bjtitus , following the steps, the feature works. I was able to export the audio, save it and listen to the clip 👍 

I left just few comments, but I have some questions:
• The first clip image goes a bit under the pagination dots. Is it expected?
• While exporting, I can still swipe between the different types. Is it correct? Because, if I export the first type, while it's exporting, I can swipe but the animation starts to be choppy.
• If I re-edit the clip while exporting, and tap on clip again, I don't see the progress anymore

2024-08-16 11:12 UTC, danielebogo commented on podcasts/Sharing/SharingModal.swift
> +                    completion(try! Data(contentsOf: progress.fileURL!), nil)
Quick one: Can we avoid the force try here?

2024-08-16 11:12 UTC, danielebogo commented on podcasts/Sharing/SharingModal.swift
> +                return [NSItemProvider(contentsOf: fileURL)!]
Same here

2024-08-16 14:24 UTC, bjtitus commented
> The first clip image goes a bit under the pagination dots. Is it expected?

Just fixed this in https://github.com/Automattic/pocket-casts-ios/pull/2045

> I can still swipe between the different types

You should only the selected style. I've fixed that in [5173479](https://github.com/Automattic/pocket-casts-ios/pull/2044/commits/51734799fc5ad55def66fce34c5e3e902719c75b)

> If I re-edit the clip while exporting, and tap on clip again, I don't see the progress anymore

The cancellation got messed up when I moved this to the `task` ViewModifier. Could you retry now? The `VideoExporter` still needs a little more work but I'll submit that separately.

2024-08-16 15:27 UTC, danielebogo approved these changes
It looks good. Thanks for fixing it after the feedback!

2024-08-16 15:30 UTC, merged