Widgets: track interaction
Automattic/pocket-casts-ios pull request #2098
Opened 2024-08-27 20:06 UTC by leandroalonso

This PR adds a new event `widget_interaction` that tracks interaction with the widgets.

## To test

1. Run a clean install of the app and enable **tracksLogging**
2. Go to the Lock Screen and add the two medium widgets
3. Both will say "Tap to Discover"
4. Tap on both
5. ✅ `widget_interaction ["action": "discover"]` should be tracked
6. Add two items to your Up Next
7. Go back to Lock screen
8. Tap the "Now playing widget"
9. ✅ `widget_interaction ["action": "now_playing"]` should be tracked
10. Go back to lock screen, tap the up next medium widget
11. ✅ `widget_interaction ["action": "up_next"]` should be tracked

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-08-27 20:06 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-28 12:15 UTC, danielebogo requested changes
Hey @leandroalonso I did some tests but not all widgets track those events:

### Lock Screen

Here I tried all widgets and I don't see events, with or without playing episodes on in the queue.

### Home Widget

If I have episodes in the queue or playing I can track these events:
• `widget_interaction ["action": "play OR pause"]`
• `widget_interaction ["action": "discover"]`
• `widget_interaction ["action": "now_playing"]`

On the biggest widget though, if I tap on the empty space available no events are tracked.

If the widgets are empty, I can only track the discover event only if I tap on the text in the middle of the widget for the medium and biggest one.

The Up next widget, the one with the cover and text on the left, doesn't track anything if the queue is empty.

The small widget always tracks the `open_app` with or without playing episodes

2024-08-28 17:16 UTC, leandroalonso commented
@danielebogo sorry, I forgot to push a few commits. :(

Lock screen should work just fine now.

> On the biggest widget though, if I tap on the empty space available no events are tracked.

This has been updated.

> The small widget always tracks the open_app with or without playing episodes

That is correct though because that's what they're doing.

This makes me wonder if we need a property with a better name. The `action` refers to what action the widget performed, like: play, pause, open app, etc.

Even though the widget is the "Now Playing", what it does is to open the app, thus the `action: open_app`. Maybe we should rename to better reflect that?

2024-08-29 09:01 UTC, danielebogo approved these changes
🎉 It worked! 🎉 
:shipit:

2024-08-29 13:38 UTC, merged