Referrals: Integrate api call for get redeem code
Automattic/pocket-casts-ios pull request #2205
Opened 2024-09-25 10:58 UTC by SergioEstevao

| 📘 Part of: #2083  |  
|:---:|

Fixes # 

## To test

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-09-25 10:58 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-26 11:07 UTC, danielebogo requested changes
Hey Sergio 2 small things for now:

• the card background is white
• the URL is posted twice

![IMG_2556](https://github.com/user-attachments/assets/da2366ff-11e5-4122-8d28-04ec6571baf9)
![IMG_2557](https://github.com/user-attachments/assets/97aa14d0-9669-40b5-9b96-de4bc69b539b)

2024-09-26 11:27 UTC, SergioEstevao commented
@danielebogo 

> the card background is white

Fixed here: https://github.com/Automattic/pocket-casts-ios/pull/2205/commits/fd2ce542983dbf93ceca58cb6909f00f99078fbd

The double url on sharing is intentional for now, I will create a separate PR to address it. I will need to set the shared items depending of the Shared to app.

2024-09-26 11:48 UTC, danielebogo approved these changes
The card background color is correct now!

2024-09-26 15:21 UTC, merged