[Widget] iOS 18: Up Next Widget support Tint Color
Automattic/pocket-casts-ios pull request #2249
Opened 2024-10-09 16:55 UTC by danielebogo

Fixes #2212 

This PR fixes the accent color when a user select the tint color in iOS 18

| Up Next no podcasts medium | Up Next no podcasts large |
| -------- | ------- |
| ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 16 28](https://github.com/user-attachments/assets/4d43efd3-8f02-404f-b613-c1cdb1a61343) |  ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 17 12](https://github.com/user-attachments/assets/eee85254-3b89-491d-805e-ae05ab3fa691) |
| Up Next medium | Up Next large |
| ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 47 00](https://github.com/user-attachments/assets/6ea1e195-8aa7-4320-9cff-80690f0ba851) |  ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 41 45](https://github.com/user-attachments/assets/ace89c80-06c7-49ac-8214-c1222c2ed66a) |
| Up Next Filter medium | Up Next Filter large |
| ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 38 11](https://github.com/user-attachments/assets/1a8067be-bbde-4293-bc95-0c408461b961) |  ![Simulator Screenshot - iPhone 16 - 2024-10-09 at 17 45 57](https://github.com/user-attachments/assets/ebfdadcd-fd63-4acc-9816-4b45d914cbfb) |

## To test

- CI must be 🟢 
- Try the Now Playing widget with all the appearances, light, dark and tint

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-10-09 16:55 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/60">7.74 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-10-10 02:32 UTC, bjtitus requested changes
@danielebogo In the smaller widget with the white background I'm seeing something weird with the Pocket Casts logo in the upper right:

![CleanShot 2024-10-09 at 20 30 00@2x](https://github.com/user-attachments/assets/2bc6be9a-0c2f-4bdf-9143-7af57dd3c5a0)

It only seems to happen with the red and white version and not the all red one:

![CleanShot 2024-10-09 at 20 31 36@2x](https://github.com/user-attachments/assets/13ccb842-c804-408f-95ff-51db083ad3e2)

2024-10-10 09:35 UTC, danielebogo commented
@SergioEstevao @bjtitus the icon is now fixed. WOuld you mind give it another look?

2024-10-10 10:45 UTC, SergioEstevao approved these changes
Tested the tint modes and now working correctly:

| 1 | 2 | 
| - | - | 
| ![Simulator Screenshot - iPhone 16 Pro - 2024-10-10 at 11 44 26](https://github.com/user-attachments/assets/89ea2915-052c-4d27-8768-66daac449283) |  ![Simulator Screenshot - iPhone 16 Pro - 2024-10-10 at 11 21 25](https://github.com/user-attachments/assets/a2aa418f-8492-43a8-a80d-e5f9edc27ed4) |

2024-10-10 15:04 UTC, bjtitus approved these changes
Looks good!

:shipit:

2024-10-10 15:04 UTC, merged