[Enhancement] Replace Subscribe with Follow
Automattic/pocket-casts-ios pull request #2356
Opened 2024-10-29 16:17 UTC by danielebogo

As discussed in our P2 we want to update some texts in few screens, to replace the word `Subscribe` with `Follow`

| Podcast Page | Podcast Page Unsubscribe | Podcast Settings |
| :------: | :------: | :------: |
| ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 31 23](https://github.com/user-attachments/assets/163821db-571b-4477-8edd-56c8d5c4bb54) | ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 31 13](https://github.com/user-attachments/assets/35836865-3d87-47f8-815d-521be7459ad1) | ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 31 59](https://github.com/user-attachments/assets/87face04-feaa-4b29-891d-d7378ad4ab54) |
| Filters All Podcast | Apply Criteria | Export Settings |
| ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 32 27](https://github.com/user-attachments/assets/ede6fae3-08d2-49d8-8e28-99d84d46ac9b) | ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 30 55](https://github.com/user-attachments/assets/c840c519-6b1a-4e4b-a76a-52ca567eff22) | ![RocketSim_Screenshot_iPhone_16_6 1_2024-10-29_16 32 44](https://github.com/user-attachments/assets/3bf9da1e-8717-4fb2-9f5e-99c06d0a748a) |

## To test

- CI musty be 🟢 
- Check the above screens

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-10-29 21:16 UTC, SergioEstevao commented
Found this message when Unfollowing a podcast.
It says `Unsubscribing` on the message when you already downloaded files:

![Simulator Screenshot - iPhone 16 Pro - 2024-10-29 at 21 14 35](https://github.com/user-attachments/assets/99325b21-a843-465d-b948-2d84b645ba22)

2024-10-29 21:31 UTC, SergioEstevao requested changes
Just found one screen that needs updating all the others have the updated text.

2024-10-30 08:08 UTC, danielebogo commented
nice catch @SergioEstevao ! I'll add it!

2024-10-30 08:40 UTC, danielebogo commented
@SergioEstevao ready for another look. I also added the instructions to test it with the FF

2024-10-30 10:19 UTC, SergioEstevao approved these changes
:shipit:

2024-10-30 10:19 UTC, merged