[Crash] Default Player crash with MTAudioProcessingTapCallbacks
Automattic/pocket-casts-ios pull request #2420
Opened 2024-11-13 20:47 UTC by danielebogo

Related to #1711

An attempt to fix the crashes related to `MTAudioProcessingTapCallbacks`.

As a tap can not be synchronously stopped, I suspect we try to access the unretained instance already deallocated.  

This solution introduces basically 3 things:
- An `AudioProcessingTapProxy` which wraps as weak the reference to the current player
- When the `MTAudioProcessingTapCallbacks` is created, the `clientInfo` is now an `UnsafeMutableRawPointer` created with the retained instance of the proxy
- We now implement the `finalize` closure where we release the previously retained tap instance

## To test

- CI must be 🟢 
- Try to play and change episodes while playing
- When the system decides to finalize the tap you will see 2 logs in this order:
1. The log from the finalize closure: `[AudioProcessingTapProxy] Finalize tap: <MTAudioProcessingTap 0x6000030513b0> Retain count 3 Created with i/f/p/u/t callbacks = {0x10aa14448/0x10aa14600/0x10aa149b4/0x10aa14d08/0x10aa15330} flags = 0x1`
2. The log from the proxy deinit: `[AudioProcessingTapProxy] Deinit proxy`
• Switch the FF off to check everything still works as before

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-11-13 20:48 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/63">7.77 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-11-13 21:52 UTC, SergioEstevao commented on podcasts/DefaultPlayer.swift
> +            if FeatureFlag.useDefaultPlayerTapCookie.enabled {
Can we encapsulate the code bellow to method and used on all places above? 
Something like: `getPlayerFromTap(_) -> DefaultPlayer`

2024-11-14 11:47 UTC, SergioEstevao requested changes
Tested this on device and it's working correctly, just left a suggestion for code improvement.

2024-11-14 14:22 UTC, danielebogo commented
Thanks @SergioEstevao . Added a static function in [22c2c8d](https://github.com/Automattic/pocket-casts-ios/pull/2420/commits/22c2c8d0dcd4740a5269c8b8992652d17578acf9)

2024-11-14 16:27 UTC, SergioEstevao approved these changes
:shipit:

2024-11-14 17:22 UTC, merged