Dismiss presented modal before showing End of Year
Automattic/pocket-casts-ios pull request #2470
Opened 2024-11-21 00:33 UTC by bjtitus

Dismisses any presented view controllers when presenting the Playback modal.

I was unable to reproduce the exact issue but I reproduced using the following patch:

[force-prompt.patch](https://github.com/user-attachments/files/17838219/force-prompt.patch)

## To test

* Apply the patch above without the changes from this branch (or just comment them out)
* Run the app
* Verify that two modals show up
* Apply the changes from this branch
* Verify that only one modal is shown

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-11-21 00:34 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-ios/milestone/63">7.77 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-11-21 10:46 UTC, danielebogo requested changes
I can still see the sheet being prompted twice.

To reproduce
- sign in with a Google / Apple account and purchase a plan
- Sign out
- Sign in again via Google or Apple and you will see the sheet prompted twice

2024-11-21 22:07 UTC, bjtitus commented
@danielebogo I updated to set the `hasShownModal` setting immediately when we present the modal instead of waiting for `onAppear` in SwiftUI. This seems to fix the duplication from what I can tell.

2024-11-22 10:33 UTC, danielebogo approved these changes
It's working now

2024-11-22 14:03 UTC, merged