[Winback]  Apply Apple API for subscription cancellation
Automattic/pocket-casts-ios pull request #2474
Opened 2024-11-21 17:04 UTC by danielebogo

| 📘 Part of: #2435
|:---:|

Fixes #2444 
Fixes #2445 

This PR uses the `StorerKit.AppStore` API to present the subscriptions panel and handle those

## To test

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2024-11-21 17:05 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-11-25 10:58 UTC, SergioEstevao commented on podcasts/CancelConfirmationViewModel.swift
> +                guard let windowScene = await navigationController.view.window?.windowScene else {
Could this code to be refactored to a separated function that could part of IAPHelper in order to better contain any StoreKit code?

2024-11-25 12:12 UTC, SergioEstevao requested changes
Functionality wise is working correctly, just asked for a code change.

2024-11-25 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=2474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=2474) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: danielebogo<br/>:x: Daniele Bogo<br/><hr/>**Daniele Bogo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-ios?pullRequest=2474) it.</sub>

2024-11-25 16:59 UTC, danielebogo commented on podcasts/CancelConfirmationViewModel.swift
> +                guard let windowScene = await navigationController.view.window?.windowScene else {
@SergioEstevao I part of it to the `IAPHandler`. All the part related to the groupID and StoreKit, so now everything is well decoupled

2024-11-26 09:26 UTC, SergioEstevao approved these changes
Thanks for addressing the suggestion! 
:shipit:

2024-11-26 10:31 UTC, merged