Track result of running SwiftLint with autocorrect
Automattic/pocket-casts-ios pull request #283
Opened 2022-09-27 05:17 UTC by mokagio

_What it says in the title_.

I did this in two commits because there were thousands of trailing whitespaces violations. 

- [The interesting one](https://github.com/Automattic/pocket-casts-ios/pull/283/commits/b27d8f29282727f3e2e43d6f72c29c712cbe681b?w=1)
- [The boring one](https://github.com/Automattic/pocket-casts-ios/pull/283/commits/780f00dd5e78ec7a15eae119d444066f6cb465b1?w=1) the link includes `?w=1` to hide whitespaces changes. You'll see that it includes only those (plus re-enabling that lint rule):

https://user-images.githubusercontent.com/1218433/192684732-8e37e34f-3944-44c4-92f2-869573324eff.mp4
_The commit in the video is not the final one, but the result is the same._

Also notice [the commit that updates the SwiftFormat settings](https://github.com/Automattic/pocket-casts-ios/pull/283/commits/c06d85575fcafdb81043630b59eaf221dbda3424#diff-716e9196614e4df70d21cfe5515e79b2695a42931ca929e2654c88e27c081245L3-L4). I had to do this in this PR otherwise the [base one](https://github.com/Automattic/pocket-casts-ios/pull/282) would have failed because of the resulting SwiftFormat violations.

There remained a few violations that couldn't be addressed directly. I thought they might be worth having a look at manually and ensuring the UI does what's expected in all cases:

- `podcasts/DateHeadingView.swift:28:20`: warning: Natural Text Alignment Violation: Forcing text alignment to left can affect the Right-to-Left layout. Consider setting it to `natural` (natural_text_alignment)
- `podcasts/SimpleActionView.swift:60:27`: warning: Inverse Text Alignment Violation: When forcing text alignment to the right, be sure to handle the Right-to-Left layout case properly, and then silence this warning with this line `// swiftlint:disable:next inverse_text_alignment` (inverse_text_alignment)
- `podcasts/WhatsNewPageView.swift:101:27`: warning: Natural Content Alignment Violation: Forcing content alignment left or right can affect the Right-to-Left layout. Use naturalContentHorizontalAlignment instead. (natural_content_alignment)
- `podcasts/WhatsNewPageView.swift:118:27`: warning: Natural Content Alignment Violation: Forcing content alignment left or right can affect the Right-to-Left layout. Use naturalContentHorizontalAlignment instead. (natural_content_alignment)
- `podcasts/WhatsNewPageView.swift:97:39`: warning: Natural Text Alignment Violation: Forcing text alignment to left can affect the Right-to-Left layout. Consider setting it to `natural` (natural_text_alignment)
- `podcasts/WhatsNewPageView.swift:115:39`: warning: Natural Text Alignment Violation: Forcing text alignment to left can affect the Right-to-Left layout. Consider setting it to `natural` (natural_text_alignment)

2022-09-28 19:45 UTC, leandroalonso requested changes
@mokagio could you please wait a bit before merging this one? There are a few changes to be merged from the release branch and I want to avoid running into any potential merge conflict due to that.

2022-10-03 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-ios?pullRequest=283) it.</sub>

2022-10-03 16:43 UTC, leandroalonso commented
@mokagio I re-ran your commands and created this: https://github.com/Automattic/pocket-casts-ios/pull/340

Hope you don't mind!

This way I can cut 7.24 without worrying about conflicts.

2022-10-03 16:43 UTC, closed without merging

2022-10-03 23:27 UTC, mokagio commented
@leandroalonso no worries at all. Good call, actually. The last thing we want is nasty merge conflicts with the release branch 👍