Migrate Crash reporting from Crashlytics to Sentry
Automattic/pocket-casts-ios pull request #359
Opened 2022-10-05 20:00 UTC by chipsnyder

Fixes #341 

Please include a summary of the changes and the related issue.

## To test

1.) Switch your scheme to "Release"
2.) Add a `fatalError` exception to the app 
3.) Build and run.
4.) Stop the run.
5.) Start the app again by selecting the icon on the home screen.
6.) Execute the code that has the `fatalError` or perform a [crash](https://github.com/Automattic/pocket-casts-ios/issues?q=is%3Aopen+is%3Aissue+label%3Acrash) repro steps.
7.) Check Sentry for the crash.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-10-05 20:58 UTC, chipsnyder commented on .configure
> +  "branch": "pc/sentry",
TODO: This needs to be updated to `trunk` before merging.

2022-10-06 19:45 UTC, chipsnyder commented
This is ready for review although we may want to time the merge with https://github.com/Automattic/pocket-casts-ios/pull/362 but that's not a hard requirement since dsyms can be uploaded manually.

2022-10-11 14:06 UTC, leandroalonso requested changes
Works as described! I left some comments about the opt-out. :)

2022-10-11 14:06 UTC, leandroalonso commented on podcasts/Analytics/Adapters/Tracks/CrashLoggingDataProvider.swift
> +        Settings.analyticsOptOut()
I don't think we want the Analytics opt-out to work for the crash analytics. we should have two different toggles: one for Analytics and another for crashes (check WPiOS for an example).

As an opt-out already doesn't exist for Firebase, I'd recommend removing opt-out in this PR and tackling in another one.

2022-10-11 14:06 UTC, leandroalonso commented on podcasts/Analytics/Adapters/Tracks/TracksAdapter.swift
> +        self.crashLogging = try? CrashLogging(dataProvider: CrashLoggingDataProvider()).start()
Similar to the comment above. Adding this call here couples the opt-out from Analytics to the crashes.

2022-10-11 14:11 UTC, chipsnyder commented
> I left some comments about the opt-out.

That works for me. I wasn't sure how deep we needed to go with the privacy settings. I'll decouple it and remove opt-out like you suggest. We can easily add it back in follow-up PRs.

2022-10-11 15:25 UTC, chipsnyder commented on podcasts/Analytics/Adapters/Crash Logging/CrashLoggingAdapter.swift
> +    func track(name: String, properties: [AnyHashable: Any]?) { }
Left as a no-op, for now, to match what Firebase was doing. If we'd like to add manual error logging levels we can do that using [these APIs](https://github.com/Automattic/Automattic-Tracks-iOS/blob/f21fcea46c2063840cccd19106fb70ab0ab6c680/Sources/Remote%20Logging/Crash%20Logging/CrashLogging.swift#L139-L229). We would probably want to identify the appropriate levels for the messages we're sending though.

2022-10-11 15:27 UTC, chipsnyder commented
@leandroalonso those changes have been applied now

2022-10-11 15:51 UTC, leandroalonso approved these changes

2022-10-11 20:39 UTC, merged