Apple SSO: Login Consolidate
Automattic/pocket-casts-ios pull request #409
Opened 2022-10-18 20:07 UTC by chipsnyder

| 📘 Project: #381 | Depends on #408 |
|:---:|:---:|

| 📓 For Apple SSO testing: In my testing, Apple SSO didn't always return the email in the simulator, so testing with a physical device is recommended. |
|:---:|

Consolidates some code paths when using the Password Auth:
- Reduces duplicated code in the obtain Token flow to use the paths created for Apple Watch and Sonos
- Moves Sync Progress updates to a shared view.

## To test
1. Log into an account with Username and Password with the `signInWithApple` feature flag enabled and disabled to ensure prod is fine.
2. ✅ Validate you are logged in successfully and the Sync Progress indicator updates with sync status changes.
3. Enable `signInWithApple`  switch to `Staging` use Apple SSO to login 
4. ✅ Validate you are logged in successfully, and the Sync Progress indicator updates with sync status changes.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-10-18 20:08 UTC, chipsnyder commented on podcasts/AppDelegate+Analytics.swift
> -            NotificationCenter.default.post(name: .userLoginDidChange, object: nil)
these items are handled in the completion of `refreshLogin`

2022-10-18 20:09 UTC, chipsnyder commented on podcasts/AuthenticationHelper.swift
> +        ServerSettings.setSyncingEmail(email: username)
Repeating saving the email here as a safety measure for Prod since the response won't have an email item yet.

2022-10-19 16:16 UTC, emilylaguna requested changes
Nice work, I tested with and without the feature flag enabled and everything works as intended. 

I left a few comments below.  Let me know what you think.

2022-10-19 16:16 UTC, emilylaguna commented on podcasts/AuthenticationHelper.swift
> +        }
From my testing if the syncing email is not set, then the rest of the sync will fail since this is used to determine if a user is logged in or not throughout the app: https://github.com/Automattic/pocket-casts-ios/blob/5e6181fa26d6e1b97dc2fd84b8fb3653f95fa048/Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift#L8

I wonder if we should we consider a nil email as a failed login?

2022-10-19 16:16 UTC, emilylaguna commented on podcasts/SyncSigninViewController.swift
> +        Analytics.track(.userSignInFailed, properties: ["source": self.authSource, "error_code": error.rawValue])
Nit: 
```suggestion
        Analytics.track(.userSignInFailed, properties: ["source": authSource, "error_code": error.rawValue])
```

2022-10-19 16:23 UTC, chipsnyder commented on podcasts/AuthenticationHelper.swift
> +        }
In general, I agree, and I think that should be the case when the endpoint changes for `user/login_apple` are merged to prod, and we can expect an email from all User Login Responses. For now, though, this acts as a safety net to not clear out the email address if it happens to be missing from the response. I'll create a clean-up task to address that for when the endpoint is available.

2022-10-20 19:00 UTC, chipsnyder commented on podcasts/AuthenticationHelper.swift
> +        }
@emilylaguna Do you have any thoughts on the plan to revisit this when the endpoint merges to prod?

2022-10-20 19:21 UTC, emilylaguna commented on podcasts/AuthenticationHelper.swift
> +        }
Thanks for creating the task, I think we can merge this in and tackle it later.

2022-10-20 19:22 UTC, emilylaguna approved these changes

2022-10-21 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=409) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-ios?pullRequest=409) it.</sub>

2022-11-02 21:48 UTC, emilylaguna commented
There are some changes coming to the login/token endpoints that will require more changes how we handle the token refresh/etc. So I am going to close this for now and revisit these improvements later.

2022-11-02 21:48 UTC, closed without merging