End of Year: sharing
Automattic/pocket-casts-ios pull request #478
Opened 2022-11-03 12:31 UTC by leandroalonso

| 📘 Project: #376 |
|:---:|

Adds text content for each story shared and for the top episode and longest episode add a link to them.

<img src="https://user-images.githubusercontent.com/7040243/199720704-b77606fe-6f08-4fb9-8300-cef66b18492b.png" width="300">

## To test

> **Note**
>
> 📱 For better testing, run this on your real device.

1. Enable `endOfYear` and `tracksLoggingEnabled` flags in `FeatureFlag.swift`
2. Run the app and make sure you're logged in to an account with a few items on Listening History
3. Check your 2022 EoY stats (either by tapping "View My 2022" on the modal or going to Profile and tapping the card there)
4. When the first story appears, tap "Share"
5. ✅ Ensure `end_of_year_story_share ["story": "intro"]` is tracked
6. Share to Notes or Twitter
7. ✅ Check the content and the image for the shared story
8. ✅ Ensure `end_of_year_story_shared ["activity": "com.apple.UIKit.activity.CopyToPasteboard", "story": "intro"]` is tracked, where activity depends on what action you've done
8. Repeat these steps for each story, always checking the events and the output (image + text)
9. ✅ For the top 1 podcast and longest episode, also make sure the link points to the correct podcast/episode

Feel free to test sharing the content to other apps.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-11-03 13:07 UTC, leandroalonso commented on podcasts/End of Year/StoryShareableText.swift
> +        if let shareUrl = Settings.top5PodcastsListLink {
I'm still not 100% sure we'll have that on the final version of the feature but it's implemented anyway, if we don't want it we'll revert commit `de46a9b144f8eae3f4cb4f6741dabd0acb9a4df0`

2022-11-03 17:23 UTC, emilylaguna requested changes
Nice work. I tested this using my real device and I noticed a few things:

- There is an extra space in front of the intro/epilogue share text
- I went to share this in my text messages and still having the social hashtag text listed there looks a bit out of place. What do you think about hiding the hash tags if we're not sharing to a social network?

I left some other nit comments on the localization descriptions as well.

2022-11-03 17:23 UTC, emilylaguna commented on podcasts/End of Year/StoryShareableText.swift
> +        self.text = "\(text) \(hashtags) \(pocketCastsUrl)"
For the intro/epilogue views with empty text this results in a blank space in the beginning of the sharing text.

2022-11-03 17:23 UTC, emilylaguna commented on podcasts/End of Year/StoriesDataSource.swift
> +    /// An optional string that identifies the story
```suggestion
    /// A string that identifies the story
```

2022-11-03 17:23 UTC, emilylaguna commented on podcasts/en.lproj/Localizable.strings
> +/* Text that appear when someone share the listened to story to Twitter, for example. %1$@ is a placeholder for the amount of time. */
```suggestion
/* Text that appears when someone shares the listened to story to Twitter, for example. %1$@ is a placeholder for the amount of time. */
```

2022-11-03 17:23 UTC, emilylaguna commented on podcasts/en.lproj/Localizable.strings
> +/* Text that appear when someone share the listened categories to story to Twitter. %1$@ is a placeholder for the number of categories. */
```suggestion
/* Text that appears when someone shares the listened categories to story to Twitter, for example. %1$@ is a placeholder for the number of categories. */
```

2022-11-03 17:40 UTC, emilylaguna reviewed
I was trying to share with Facebook and the text gets broken for some reason. 

<img src="https://user-images.githubusercontent.com/793774/199794950-3d9d6fb0-df9c-4e81-8418-ab337574ca2a.jpeg" height="320" />

2022-11-03 19:17 UTC, leandroalonso commented on podcasts/End of Year/StoryShareableText.swift
> +        self.text = "\(text) \(hashtags) \(pocketCastsUrl)"
Fixed here https://github.com/Automattic/pocket-casts-ios/pull/478/commits/7d3e44dffef5e81d46f581a2e55b17c560943774#diff-1474c68d91e2337b9994c006a5c6a9364c5da6c04cd1c3996edcfd4c0e0cb0cdR53

2022-11-04 13:58 UTC, emilylaguna approved these changes

2022-11-04 18:02 UTC, merged