End of Year: sync Listening History
Automattic/pocket-casts-ios pull request #483
Opened 2022-11-04 14:49 UTC by leandroalonso

| 📘 Project: #376 |
|:---:|

**The PR is not ready for review because we need the `playedUpTo` property returned.**

If we identify the user doesn't have the entire 2022 listening history, we sync this with the server adding the missing episodes.

This is a case that might happen for a very active user that switched devices during this year — given we only sync the latest 100 items.

## To test

There are two ways to test it:

1. The real way, which would require you to "play" more than a 100 episodes
2. The fake way, in which you can manipulate the code to simulate this state

### Real way

1. Play more than 100 episodes on your account
2. Delete the app
3. Run the app again
4. Check your End of Year stats
5. You should see the spinner while the episodes load
6. ✅ Stories should appear after everything sync

### Fake way

TBD

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-11-04 20:32 UTC, leandroalonso commented on Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
> +                            playedUpTo > 300 AND
If a user had listened to multiple episodes with less than 30 minutes they were not eligible, I changed that to just 5 minutes.

2022-11-04 20:33 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +class PodcastExistHelper {
I created this to avoid calling the database over and over to check if an episode exists.

2022-11-07 08:14 UTC, Ferdev commented
Hey @leandroalonso!
> A much more bulletproof strategy would be to call the endpoint to check the number of items for the user, and sync if needed, just once. But I'm not sure what would be the impact of such a call on the backend (@Ferdev curious to hear your thoughts about it)

I don't think it would be a problem if we just call it once. The database query is pretty simple and the whole request doesn't execute any crazy calculations, so we should be fine if we just run it one time :+1: .

2022-11-07 17:52 UTC, emilylaguna requested changes
Heya! This worked well in my testing. I left some comments, let me know what you think.

2022-11-07 17:52 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +        dataToSync.year = 2022
What do you think about allowing this to be injected?

2022-11-07 17:52 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +        let uniqueUuidsToUpdate = Array(Set(podcastsToUpdate))
Instead of converting the array -> set -> array. What do you think about just changing podcastsToUpdate to a Set?

`var podcastsToUpdate: Set<String> = []`

2022-11-07 17:52 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +    }
This doesn't seem to be used, should we remove it?

2022-11-07 17:52 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +class PodcastExistHelper {
Nit: 
```suggestion
class PodcastExistsHelper {
```

2022-11-07 17:52 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +            if let response = response, httpStatus == ServerConstants.HttpConstants.ok {
Nit: 
```suggestion
            if let response, httpStatus == ServerConstants.HttpConstants.ok {
```

2022-11-07 18:26 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +        dataToSync.year = 2022
Done in 9001df4ea623989bf8817411c56c2ddb6e85e0a4

2022-11-07 18:26 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +        let uniqueUuidsToUpdate = Array(Set(podcastsToUpdate))
Done in fecb93b21f5195525be729b208bb70c9aa94148b

2022-11-07 18:26 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +    }
Done in 194ddece6dbffacc694d6c9be8a12dde2f04598d

2022-11-07 18:26 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +class PodcastExistHelper {
Done in 21f03cb5f02e7962c5cb7a00d451b1685f0f7996

2022-11-07 18:26 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
> +            if let response = response, httpStatus == ServerConstants.HttpConstants.ok {
Done in fdd751b6a44ff5613e559ba8b30e585eb37ce88c

2022-11-07 19:03 UTC, emilylaguna approved these changes

2022-11-07 19:04 UTC, merged