Make custom time stepper more accessible
Automattic/pocket-casts-ios pull request #509
Opened 2022-11-12 08:48 UTC by adincebic

Improves the usability of time stepper through out the app and makes it way easier to navigate through screens like settings.

## To test

1. Launch the app
2. Go to profile tab
3. Tap on settings
4. Tap on general
5. Turn voiceover on if you didn't turn it on already
6. Use swipe right gesture to get to the cell with time stepper (i.e. skip forward cell in player section)
7. When you hear current skip forward value (i.e. 45 seconds) swipe right once more and you should hear voiceover pronounce "adjustable" or "slider"
8. Use swipe up or down voiceover gestures to adjust the value

This significantly improves the experience for voiceover users and makes it much easier to navigate through settings screen.

2022-11-17 06:27 UTC, adincebic commented
@emilylaguna  could you take a look at this PR?

2022-11-21 21:46 UTC, jgcaruso commented
This tested really well, and does feel like a big improvement over the previous VoiceOver experience.

I don't have commit permission on this repo, so I'll leave it to @emilylaguna for final review.

2022-11-21 22:54 UTC, emilylaguna requested changes
👋 Sorry for the delay in my review!

I took a look at this it's working well except for 1 thing. When I swipe up to have a value that is more a minute or more, VO reads it out as "1 meter" and if it has seconds it reason "1 meter 5 ess" or "1 meter 10's"

I left a comment below on how we can fix this.

2022-11-21 22:54 UTC, emilylaguna commented on podcasts/CustomTimeStepper.swift
> +            accessibilityValue = L10n.timeShorthand(Int(currentValue))
We can use the `localizedTimeDescription` to read out the full time value instead of the shorthand. 

```suggestion
            accessibilityValue = currentValue.localizedTimeDescription ?? ""
```

2022-11-21 22:56 UTC, emilylaguna commented on podcasts/CustomTimeStepper.swift
> +            accessibilityValue = L10n.timeShorthand(Int(currentValue))
Here's a video of the values VO is reading out:

https://user-images.githubusercontent.com/793774/203174415-6792c994-2e5d-4d49-a504-f0d0a4bc7012.mov

2022-11-23 07:49 UTC, adincebic commented on podcasts/CustomTimeStepper.swift
> +            accessibilityValue = L10n.timeShorthand(Int(currentValue))
Hey @emilylaguna good that you caught it. I will get on it probably in a few days. This is something that I really want to get right.

2023-05-08 16:24 UTC, CookieyedCodes commented
@adincebic want to come back to this?

2023-05-08 16:27 UTC, adincebic commented
Yes, thanks for reminding me.> @adincebic want to come back to this?

2023-05-13 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=509) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: adincebic<br/>:x: Adin Ćebić<br/><hr/>**Adin Ćebić** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Automattic/pocket-casts-ios?pullRequest=509) it.</sub>

2023-05-13 12:35 UTC, adincebic commented on podcasts/CustomTimeStepper.swift
> +            accessibilityValue = L10n.timeShorthand(Int(currentValue))
Hey @emilylaguna I finally got around to fixing this. Sorry for the huge delay. Please check it out.

2023-05-13 12:37 UTC, adincebic commented
> @adincebic want to come back to this?

Finally finished it. Again thanks for the reminder.

2023-05-15 22:21 UTC, emilylaguna approved these changes
Nice work! Sounds good to me now!

2023-05-16 00:01 UTC, merged