Support hidden chapters
Automattic/pocket-casts-ios pull request #553
Opened 2022-11-29 09:16 UTC by maarut

Fixes #

Added support for hidden chapters (hidden chapters don't show up in the Table Of Contents).
When scrubbing through the timeline, chapter titles, URLs and images are updated based on the position of the playhead.

## To test

I tested using the Stratechery Podcast episode dated 25th October 2022. It has multiple hidden chapters with images.

## Checklist

- [*] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [*] I have considered adding unit tests for my changes.
- [* ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-11-29 09:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Automattic/pocket-casts-ios?pullRequest=553) <br/>All committers have signed the CLA.

2022-11-29 09:29 UTC, maarut commented
[This is the first time I've submitted a PR for an open source project. Please advise if I haven't correctly followed your processes. I can close this PR and re-create a new one following the proper process if necessary]

2022-11-29 15:20 UTC, emilylaguna requested changes
👋 Hi @maarut, Thank you so much for your contribution! We are super thrilled that you chose to contribute to Pocket Casts for your **first ever** OSS project! 

Since this PR has a lot of changes we will need to do some extra testing on our end so our reviews may be a bit delayed. However I did a quick review and left some comments below. 

In addition to the comments below, I think these changes could benefit from adding some unit tests to make sure everything works as intended.

Let me know what you think.

2022-11-29 15:20 UTC, emilylaguna commented on podcasts/Chapters.swift
> +
Can you remove the header from this file?

2022-11-29 15:20 UTC, emilylaguna commented on podcasts/Chapters.swift
> +import Foundation
```suggestion
```

Since UIKit already includes Foundation we don't need to double the imports up

2022-11-29 15:20 UTC, emilylaguna commented on podcasts/Chapters.swift
> +    }
We can reduce the overall code changes by making these all be read-only computed properties.

2022-11-29 15:20 UTC, emilylaguna commented on podcasts/Chapters.swift
> +    init(chapters: [ChapterInfo]) {
I see elsewhere in the code you're init'ing with an empty array. I think we can clean up the code by adding a default value, that way you can just do `Chapters()`

```suggestion
    init(chapters: [ChapterInfo] = []) {
```

2023-01-09 22:31 UTC, maarut commented on podcasts/Chapters.swift
> +
I've removed all copyright notices.

2023-01-09 22:32 UTC, maarut commented on podcasts/Chapters.swift
> +import Foundation
I've removed superfluous imports

2023-01-09 22:32 UTC, maarut commented on podcasts/Chapters.swift
> +    }
I've reworked this code to be computed properties.

2023-01-09 22:33 UTC, maarut commented on podcasts/Chapters.swift
> +    init(chapters: [ChapterInfo]) {
Default value defined on init.

2023-01-09 22:36 UTC, maarut commented
@emilylaguna Thanks for providing review comments and suggestions for improvements. Sorry for the delay, but I think I have addressed all outstanding comments. I hope this gets us a step closer to merging the PR.

2023-01-23 23:26 UTC, emilylaguna requested changes
Hey! Thanks for making the edits, the code is shaping up nicely. 

I left a few more comments below, along with some questions. 

Please let me know what you think.

2023-01-23 23:26 UTC, emilylaguna commented on podcasts/ChapterManager.swift
> +    var currentChapters: Chapters = Chapters()
We can remove the Chapters type here since it's inferred from the `Chapters()` init.

```suggestion
    var currentChapters = Chapters()
```

2023-01-23 23:26 UTC, emilylaguna commented on podcasts/Chapters.swift
> +private func chaptersOverlap(_ chapters: [ChapterInfo]) -> Bool {
While this does work, the preferred way to accomplish this would be to use a private extension like:

```suggestion
private extension Chapters {
    func chaptersOverlap(_ chapters: [ChapterInfo]) -> Bool {
```

2023-01-23 23:26 UTC, emilylaguna commented on podcasts/Chapters.swift
> +            return nil
Maybe a dumb question, but could you explain the purpose of doing the chapters overlap check and why we want to return nil if they don't overlap?

2023-01-23 23:26 UTC, emilylaguna commented on podcasts/Chapters.swift
> +    var ranegsOverlap = true
Small typo here. 

```suggestion
    var rangesOverlap = true
```

2023-01-23 23:26 UTC, emilylaguna commented on podcasts/Chapters.swift
> +        }
Since the `chapters` property already sets itself to an empty array we can remove the need for an optional and just only set the property if the overlap check succeeds like so:

```suggestion
    init(chapters: [ChapterInfo] = []) {
        if chaptersOverlap(chapters) {
            self.chapters = chapters
        }
    }
```

2023-01-26 22:30 UTC, maarut commented on podcasts/Chapters.swift
> +            return nil
The purpose of the class is to represent the chapters for an audio file at a given playback position. Given this purpose, if the chapters don't overlap over that given playback position, then the query used to extract the chapters isn't valid for the use of this class.

2023-01-26 23:13 UTC, maarut commented on podcasts/ChapterManager.swift
> +    var currentChapters: Chapters = Chapters()
Removed type specification

2023-01-26 23:13 UTC, maarut commented on podcasts/Chapters.swift
> +private func chaptersOverlap(_ chapters: [ChapterInfo]) -> Bool {
Moved code in to a private class extension as suggested.

2023-01-26 23:13 UTC, maarut commented on podcasts/Chapters.swift
> +    var ranegsOverlap = true
Typo corrected.

2023-01-26 23:14 UTC, maarut commented on podcasts/Chapters.swift
> +        }
Adopted suggested code.

2023-02-08 13:59 UTC, maarut commented
Sorry for the delay in submitting a summary comment, but I have addressed the simple code related improvements you suggested, and responded to your query around the Chapters class.

2023-04-24 13:47 UTC, CookieyedCodes commented
@emilylaguna should this be merged now?

2023-04-26 14:30 UTC, emilylaguna approved these changes
Hey @maarut! I apologize, I didn't see your reply and this slipped off my radar. 

I've retested and all looks good. 

I have [made a PR](https://github.com/Automattic/pocket-casts-ios/pull/839) that merges trunk into the PR and moves the changes in the CHANGELOG to the new version, once that is 🟢 on the CI I'll merge it in. 

Thank you for your contribution and patience.

2023-04-27 14:50 UTC, merged

2023-04-27 19:34 UTC, maarut commented
Thanks for accepting my contribution! No worries about the delay.

2023-05-31 18:22 UTC, leandroalonso commented
@maarut JFYI, we're reverting the changes made here for the next release: https://github.com/Automattic/pocket-casts-ios/pull/883

While there isn't a problem per se with the code, we had a feature regression and there are a few reports coming in about the missing chapter information — that used to be available.

What I think we can do is reopen this PR making sure that:

1. Episodes that show chapters still show them even after this change;
2. The "Chapters" tab shows the chapter progress
3. The full-player controller has the UI for navigating through chapters

I am more than happy to test and review these changes if you create a PR. :)