End Of Year: Implement Design Notes Feedback for the Intro Story
Automattic/pocket-casts-ios pull request #557
Opened 2022-11-30 18:19 UTC by emilylaguna

| 📘 Project: #376 |
|:---:|

#### Text Changes:
- Increases line height to 2.5 to better match the design
- Replaces typewriter apostrophes `'` with typographic ones `’`
- Replaces `...` with `!`
- Inserts a newline between `...your year` and `of ...` to prevent widows

#### UI Changes
- Moves the 2022 logo down, it is now 10% from the top of the view
- Reduces the logo bottom padding from 40 to 24
   - This applies to all stories
- Increased share button leading/trailing padding to 20 from 5
    - This applies to all stories, not seen in below screenshots

#### Code changes
- Created a new common view for the logo and applied it to all stories

## Screenshots

### Design vs Implementation Comparison
<p align="center"><img src="https://user-images.githubusercontent.com/793774/204874353-e0c362ab-bfb9-476f-a1c1-4f050476f02b.png" width="100%" /></p>

### Devices
| iPhone SE - 14.1 | iPhone 13 | iPhone 14 Pro Max |
|:---:|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/793774/204876594-79308aa5-2e68-416e-a932-b0d74c5a009c.png" width="320" />|<img src="https://user-images.githubusercontent.com/793774/204876672-84eebbd6-d636-4b79-bf8e-86fedeae67bd.png" width="320" />|<img src="https://user-images.githubusercontent.com/793774/204876656-54d0859a-8476-4bc1-bed4-d3950f077784.png" width="320" />|

## To test

1. Launch the app
2. Go to the Profile Tab
3. Tap on the End of Year Card
4. ✅ Verify the Intro Story matches the designs (See comparison above)
7. Tap through to the other stories
8. ✅ Verify the Logo appears in a consistent location on each of them (except for the final view, will be updated later)
5. Launch the app on various device sizes
6. ✅ Verify the view still looks good on all of them

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-11-30 22:16 UTC, jgcaruso requested changes
Code changes look good (I'm assuming the ShareableStore code matches https://github.com/Automattic/pocket-casts-ios/pull/555 so I didn't scrutinize it too much this time) and the Intro screen on device matches the design.

Something is up with smaller screens though (iPhone 6S, not on 13 mini so possibly not a device we're overly concerned about). This PR vs #555 causes an overlap on the `TopFivePodcastsStory` screen

| before (#555) | after (this pr) |
|-----|-----|
| ![IMG_0008](https://user-images.githubusercontent.com/4081020/204919643-899d0819-9807-47e4-9eed-67a2d033375f.PNG) |  ![IMG_0007](https://user-images.githubusercontent.com/4081020/204919638-3673d8ac-48aa-4c58-ab6b-f378648b9e5e.PNG) |

2022-11-30 22:16 UTC, jgcaruso commented on podcasts/End of Year/Stories/Views/PodcastCover.swift
> +            .shadow(color: .black.opacity(0.01 + 0.2), radius: 4, x: 0, y: 11)
can `0.2` be a constant somewhere?

2022-11-30 22:16 UTC, jgcaruso commented on podcasts/End of Year/Stories/Views/PodcastCover.swift
> +            .shadow(color: .black.opacity(0.01 + 0.2), radius: 27, x: 0, y: 67)
can `0.2` be a constant somewhere?

2022-11-30 22:18 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/PodcastCover.swift
> +            .shadow(color: .black.opacity(0.01 + 0.2), radius: 27, x: 0, y: 67)
Oops. That wasn't meant to be committed. Reverted it here: ba7b640a5898c13a9a5a6b6013c5429308bdb034

2022-11-30 22:18 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/PodcastCover.swift
> +            .shadow(color: .black.opacity(0.01 + 0.2), radius: 4, x: 0, y: 11)
Oops. That wasn't meant to be committed. Reverted it here: ba7b640a5898c13a9a5a6b6013c5429308bdb034

2022-12-01 00:24 UTC, emilylaguna commented
> Something is up with smaller screens though (iPhone 6S and SE but not on 13 mini ). This PR vs #555 causes an overlap on the `TopFivePodcastsStory` screen

Yeah, this is because the share logo is absolutely positioned over the entire view. I'm planning on fixing that screen in a future pr.

2022-12-01 14:45 UTC, jgcaruso approved these changes
Latest change and comments re: logo LGTM!

2022-12-01 15:06 UTC, merged