End of Year: Implements design feedback for the listened numbers story
Automattic/pocket-casts-ios pull request #562
Opened 2022-12-02 06:30 UTC by emilylaguna

| 📘 Project: #374 | 🛫 Depends on: #561 |
|:---:|:---:|

This addresses the following items:
- Moves "kept" to a new line
- Updates the fonts
- Adjusts spacing between the covers
- I did not scale the covers up in size because the image assets we have became blurry.

## Screenshots

### Design vs Implementation Comparison

<p align="center"><img src="https://user-images.githubusercontent.com/793774/205229629-8e5b7841-b6c8-48a5-876e-0d07dd4687fc.png" width="100%" /></p>

### Devices
| iPhone SE - 14.1 | iPhone 13 | iPhone 14 Pro Max |
|:---:|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/793774/205229714-bb38735c-70f1-450c-a049-3ab3d7b675e8.png" width="320" />|<img src="https://user-images.githubusercontent.com/793774/205229715-0113c896-303e-4fcd-9651-070c92dbe439.png" width="320" />|<img src="https://user-images.githubusercontent.com/793774/205229711-c248d155-c508-4877-928b-c418fa5c20d6.png" width="320" />|

## To test

1. Launch the app
2. Tap on Profile > End of Year card
3. Tap to the 5th screen
4. ✅ Verify it looks good and matches the designs
5. ✅ Repeat the steps of various screen sizes

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2022-12-02 06:31 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/CommonStoryViews.swift
> +struct PodcastPerspectiveRotator<Cover: View>: View {
This solves a problem when applying rotation effects which messes up the view's frame. This instead will calculate the proper height for it and reapply it after the rotation effect takes place.

2022-12-05 12:21 UTC, leandroalonso requested changes
Tested and it looks good, but we're using the podcast text for the episodes.

2022-12-05 12:21 UTC, leandroalonso commented on podcasts/End of Year/Stories/ListenedNumbersStory.swift
> +                let episodes = L10n.eoyStoryListenedToPodcastText(listenedNumbers.numberOfEpisodes)
```suggestion
                let episodes = L10n.eoyStoryListenedToEpisodeText(listenedNumbers.numberOfEpisodes)
```

2022-12-05 16:15 UTC, emilylaguna commented on podcasts/End of Year/Stories/ListenedNumbersStory.swift
> +                let episodes = L10n.eoyStoryListenedToPodcastText(listenedNumbers.numberOfEpisodes)
Ah I made a change to fix that, but I don't see it anywhere in my commits. Fixed here: d7aa9e909552b97ec5f26e04d7b7a0deb9accc42

2022-12-05 16:18 UTC, leandroalonso approved these changes

2022-12-05 16:41 UTC, merged