SSO: Add Apple Login
Automattic/pocket-casts-ios pull request #652
Opened 2023-01-18 17:07 UTC by leandroalonso

| 📘 Project: #381 |
|:---:|

* Adds Apple login
* Refactor the code so adding other providers in the future is easier

## To test

Steps to test your PR.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-01-19 17:49 UTC, emilylaguna requested changes
Works nicely, I was able to sign in using an existing and new account. 

I left a few comments below. 

Also, since the notification observer logic has been changed do we still need the `loginFinished` code in the LoginCoordinator?

2023-01-19 17:49 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        navigationController?.presentedViewController?.dismiss(animated: true)
If I open the SSO flow and then cancel it, the error is still shown.

2023-01-19 17:49 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +                newAccountCreated = response?.isNewAccount ?? false
What about moving this at the end since the refresh won't start until the next runloop, and this will ensure that we only add the listeners once the user has actually successfully signed in. 

```suggestion
                let response = try await self.socialLogin?.login()
                newAccountCreated = response?.isNewAccount ?? false
                listenToSync()
```

2023-01-19 19:40 UTC, leandroalonso commented on podcasts/Onboarding/LoginCoordinator.swift
> +        navigationController?.presentedViewController?.dismiss(animated: true)
I addressed this in b80f2a00105c23f619ba665effd8610c074636cd

Let me know what you think of the solution.

2023-01-23 18:27 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        navigationController?.presentedViewController?.dismiss(animated: true)
Looks good.

2023-01-23 18:29 UTC, emilylaguna approved these changes
Nice work!

2023-01-23 18:31 UTC, merged