SSO: show onboarding with new SSO buttons when logged out
Automattic/pocket-casts-ios pull request #674
Opened 2023-01-26 18:47 UTC by leandroalonso

| 📘 Project: #381 |
|:---:|

Changes the logged-out flow to show the new onboarding screen with Apple and Google buttons.

## To test

2. Go to `podcasts` scheme and change Build Configuration to `Debug`
3. On the app, go to Settings > Beta Features > enable `signInWithApple`
3. Login (using username/password)
4. Go to `podcasts` scheme and change Build Configuration to `Staging`
4. Re-run the app
4. Go to Profile > tap "Refresh Now"
4. You should see the logged-out modal, tap "Log in"
4. Login with username/password, Google or Apple
4. ✅ The login should work successfully and the onboarding flow should dismiss

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-01-26 22:27 UTC, emilylaguna requested changes
Nice work. I found a bug with reusing the existing `loggedOut` flow causing the upsell prompt to no longer show when logging in via the Profile tab. 

Instead of reusing an existing flow, we should add a new one such as `loggedOutNeedsLogin` so we can:
- Add specific handling for this state
- Have better context of how people sign in via this flow.

I also left a comment about using the same logic on the account created handler as well.

2023-01-26 22:27 UTC, emilylaguna commented on podcasts/Onboarding/OnboardingFlow.swift
> +            case .sonosLink, .loggedOut:
Unfortunately reusing the `loggedOut` flow here causes the normal logged out flow to no longer prompt for Plus. You can test this by:

1. Launch the app
2. Stay signed out
3. Tap the account button on the Profile tab
4. Sign in using username/password that doesn't have plus
5. 💥 The plus prompt is no longer shown

2023-01-26 22:27 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        let shouldDismiss = OnboardingFlow.shared.currentFlow.shouldDismiss || (SubscriptionHelper.hasActiveSubscription() && !presentedFromUpgrade)
I think we should also apply the `OnboardingFlow.shared.currentFlow.shouldDismiss` to the `handleAccountCreated` check below as well.

2023-01-27 13:01 UTC, leandroalonso commented on podcasts/Onboarding/LoginCoordinator.swift
> +        let shouldDismiss = OnboardingFlow.shared.currentFlow.shouldDismiss || (SubscriptionHelper.hasActiveSubscription() && !presentedFromUpgrade)
Ops I forgot to push 😅 2c61d832c41f27c38f47d4b6b54ca01a6270a02f

2023-01-27 17:46 UTC, emilylaguna approved these changes
Nice work, this is working nicely for me now. I left 1 comment about improving the documentation comment, but it's not blocking.

2023-01-27 17:46 UTC, emilylaguna commented on podcasts/Onboarding/OnboardingFlow.swift
> +        /// When the user was logged in but was forced logged out
Wdyt about adding some more info to the comment?
```suggestion
        /// When the user was logged out due to a server or token issue, not as a result of user interaction and is
        /// asked to sign in again. See the `BackgroundSignOutListener`
```

2023-01-27 17:57 UTC, merged