SSO: add Tracks
Automattic/pocket-casts-ios pull request #679
Opened 2023-01-30 17:03 UTC by leandroalonso

| 📘 Project: #381 |
|:---:|

Track logins/account creation made with Apple/Google.

I decided to refactor the code a little bit and move events to be close to the view. Before it was closer to the backend calls, and that might end up creating issues such as triggering the event when we didn't want to or making it hard to change that in the future.

While this approach duplicates some events being triggered, I think it's better than having a flag that go through multiple methods.

## To test

1. Delete any previous account you might have on Staging for your Google/Apple credentials
1. Do a clean run on the app
1. Go to Profile > Settings > Beta Features > Enable `tracksLogging` and `signInWithApple`
1. Go to Profile > tap bubble account at the top then tap "Sign Up"
1. Create a new account
1. ✅ `user_signed_in` and `user_account_created` should be tracked with `["source": "password"]`
1. Log out
1. Login with the account you just created
1. ✅ Ensure `Tracked: user_signed_in ["source": "password"]` is tracked but `user_account_created` is not
1. Log out
1. Tap the Google button
1. ✅ Ensure `Tracked: sso_started ["source": "google"]` is tracked
1. Create an account
1. ✅ `user_signed_in` and `user_account_created` should be tracked with `["source": "google"]`
1. Log out
1. Login with your Google account
1. ✅ Ensure `Tracked: user_signed_in ["source": "google"]` is tracked but `user_account_created` is not
1. Log out
1. Tap the Apple button
1. ✅ Ensure `Tracked: sso_started ["source": "apple"]` is tracked
1. Create an account
1. ✅ `user_signed_in` and `user_account_created` should be tracked with `["source": "apple"]`
1. Log out
1. Login with your Apple account
1. ✅ Ensure `Tracked: user_signed_in ["source": "apple"]` is tracked but `user_account_created` is not

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-01-30 17:07 UTC, leandroalonso commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.userSignInFailed, properties: ["source": socialAuthProvider?.rawValue ?? "password", "error_code": (error as NSError).code])
We also have the `user_account_creation_failed` event. However, there's no way to know if the user is signing in or creating an account for SSO. So I decided to use `userSignInFailed`.

2023-01-31 16:58 UTC, emilylaguna requested changes
I gave this a test and it's working correctly with the exception of a few items that I left comments on below.

2023-01-31 16:58 UTC, emilylaguna commented on podcasts/NewEmailViewController.swift
> +                    Analytics.track(.userSignedIn, properties: ["source": "password"])
Is there a reason we're adding the user signed in event on account creation?

The user signed in event trigger is defined as:
> "When the user successfully signs into the app using **existing credentials** as the result of a direct user action."

2023-01-31 16:58 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.ssoStarted, properties: ["source": provider.rawValue])
Instead of using the rawValue, we should add `AnalyticsDescribable` to the `SocialAuthProvider`. 

Since it's in a module, it can be added to [AnalyticsDescribable+Modules.swift](https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/Analytics/AnalyticsDescribable%2BModules.swift).

2023-01-31 16:58 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
> +public enum SocialAuthProvider: String, CaseIterable {
I don't think we need the String type if we add an extension to conform to `AnalyticsDescribable` (see comment below)

2023-01-31 19:45 UTC, leandroalonso commented on podcasts/NewEmailViewController.swift
> +                    Analytics.track(.userSignedIn, properties: ["source": "password"])
Fixed in 742cdc0225c6d70d961d8d90a00cfb6667ae7d38

2023-01-31 19:45 UTC, leandroalonso commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.ssoStarted, properties: ["source": provider.rawValue])
Done in db5265dca6af9235be63535a2fa59f4a26142913

2023-01-31 19:45 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
> +public enum SocialAuthProvider: String, CaseIterable {
Done in db5265dca6af9235be63535a2fa59f4a26142913

2023-01-31 20:32 UTC, emilylaguna requested changes
Since the Analytics.track automatically converts the `AnalyticsDescribable` we don't need to specify the `analyticsDescription`.

2023-01-31 20:32 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.userSignInFailed, properties: ["source": socialAuthProvider?.analyticsDescription ?? "password", "error_code": (error as NSError).code])
```suggestion
        Analytics.track(.userSignInFailed, properties: ["source": socialAuthProvider ?? "password", "error_code": (error as NSError).code])
```

2023-01-31 20:32 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.userAccountCreated, properties: ["source": socialAuthProvider?.analyticsDescription ?? "password"])
```suggestion
        Analytics.track(.userAccountCreated, properties: ["source": socialAuthProvider ?? "password"])
```

2023-01-31 20:32 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +        Analytics.track(.ssoStarted, properties: ["source": provider.analyticsDescription])
```suggestion
        Analytics.track(.ssoStarted, properties: ["source": provider])
```

2023-02-01 15:38 UTC, emilylaguna approved these changes
👍 I left a suggestion to remove a `analyticsDescription` that was missed. 

Good to go after that.

2023-02-01 15:38 UTC, emilylaguna commented on podcasts/Onboarding/LoginCoordinator.swift
> +                    Analytics.track(.userSignedIn, properties: ["source": provider.analyticsDescription])
```suggestion
                    Analytics.track(.userSignedIn, properties: ["source": provider])
```

2023-02-01 15:40 UTC, merged