Search Improvements: show podcasts and episodes
Automattic/pocket-casts-ios pull request #766
Opened 2023-03-07 18:58 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Display the podcasts and episodes when performing a search.

## To test

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Go to Discover ¶
4. Tap the search input
5. Enter any term
6. ✅ Podcasts and episodes should reflect what you searched
7. Change your search term
8. ✅ The results should change
9. Type any random string
10. ✅  You should see a message that no episodes or podcasts were found

¶ The search is not 100% functional from Podcasts and this will be fixed in a subsequent PR. I avoided doing that now because it would affect the current search.

## Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-07 19:52 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Search/EpisodeSearchTask.swift
> +        let json: [String: Any] = ["term": term.replacingOccurrences(of: " ", with: "+")]
Without this, no episodes were being returned to me.

2023-03-08 19:20 UTC, emilylaguna requested changes
Awesome job, this is shaping up nicely. 

I left a few comments below, let me know what you think.

2023-03-08 19:20 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/EpisodeSearchTask.swift
> +    public init() {}
Wdyt about allowing injecting of the URLSession?

```suggestion
    private let session: URLSession

    public init(session: URLSession = .shared) {
        self.session = session
    }
```

2023-03-08 19:20 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/EpisodeSearchTask.swift
> +}
Do we need this to be public? I'm only seeing it used in the `EpisodeSearchResult` and we're just returning the `episodes` value in the search method.

2023-03-08 19:20 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +
Same suggestion about injecting the session. 

```suggestion
    private let session: URLSession

    public init(session: URLSession = .shared) {
        self.session = session
    }
```

2023-03-08 19:20 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/EpisodeSearchTask.swift
> +        let jsonData = try? JSONSerialization.data(withJSONObject: json)
Since this call throws, should we remove the `?`?
```suggestion
        let jsonData = try JSONSerialization.data(withJSONObject: json)
```

2023-03-08 19:20 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +        let jsonData = try? JSONSerialization.data(withJSONObject: json)
Same as from the episode task:

```suggestion
        let jsonData = try JSONSerialization.data(withJSONObject: json)
```

2023-03-08 19:20 UTC, emilylaguna commented on podcasts/End of Year/Stories/Views/PodcastCover.swift
> +    var podcastUuid: String
I don't see this modified anywhere, do we need this to be a var still?

2023-03-08 19:20 UTC, emilylaguna commented on podcasts/New Search/Model/SearchResultsModel.swift
> +        Task.init {
[Nit] 

```suggestion
        Task {
```

2023-03-08 19:20 UTC, emilylaguna commented on podcasts/New Search/Model/SearchResultsModel.swift
> +        Task.init {
[Nit]

```suggestion
        Task{
```

2023-03-08 19:20 UTC, emilylaguna commented on podcasts/New Search/SearchResultsViewController.swift
> +import PocketCastsServer
Do we still need this import?

2023-03-09 16:22 UTC, emilylaguna approved these changes
:shipit:

2023-03-09 18:18 UTC, merged