Search Improvements: add interactions with podcasts/episodes
Automattic/pocket-casts-ios pull request #769
Opened 2023-03-08 17:32 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

When showing search results, add interactions for podcasts/episodes.

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`

### Podcasts

1. Go to discover
1. Search for anything
1. Tap on the podcast image
1. ✅ The podcast details screen should show
1. Go back and tap on the title/author
1. ✅ The podcast details screen should show
1. Tap the "+" button
1. ✅ You should subscribe to the podcast

### Episodes

1. Go to discover
1. Search for anything
1. Tap on any episode
1. ✅ The episode should load
1. Interact with the buttons and make sure everything is working
1. Go back
1. ✅ Make sure "Show all" is not shown for episodes

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-08 19:19 UTC, leandroalonso commented on podcasts/New Search/Views/Results/SubscribeButtonView.swift
> +    private func subscribe() {
I'm debating whether I should create a model or not for this.

While I think this is the correct approach, should we do something so simple? Open to feedback.

2023-03-08 23:47 UTC, emilylaguna requested changes
I gave this a test and overall it works very well, but I did hit an issue. 

### Issue:

For some episodes I am getting stuck on the loading screen without anything else happening. 

<details>
  <summary>Demo Video</summary>
  
https://user-images.githubusercontent.com/793774/223874850-131fa14c-9531-46ec-a4c2-0764a67692c2.MP4
  
</details>

I did some digging and it turns out even after the add podcast code has ran the episode is still nil when it's being returned from the database. 

I think this issue happens when I load an episode for a podcast and then try to load another episode that's missing from the database for the same podcast. 

I think we need to change how we're adding the episode/podcast to use the:

`ServerPodcastManager.shared.addMissingPodcastAndEpisode` and the `ServerPodcastManager.shared.addMissingEpisode` to make sure it's actually added

Then display an error if the loading fails. 

### Idea

Looking through the changes in the PR to add async loading to the EpisodeDetailViewController has me a bit worried about some potential other issues that could pop up when the controller is being used elsewhere. While I don't have a specific example it's just a general concern. 

I did have a thought about how we could accomplish this but without effecting the existing code as much by having a loading view controller just for loading the episode, and then pushing to the episode controller once it's done. 

This would be done by wrapping the loading + episode controller in a navigation controller, and hiding the nav bar. 

I made a quick concept and pushed it here: https://github.com/Automattic/pocket-casts-ios/compare/issue/709-show-search-results...idea/episode-async-loading

Let me know what you think.

2023-03-09 12:59 UTC, leandroalonso commented
> Let me know what you think.

@emilylaguna  I agree. I applied your solution and changed it to handle episodes failing to load and supporting themes.

Ready for another 👀

2023-03-09 17:03 UTC, emilylaguna approved these changes
🎉 Nice work, gave this a test and all is working well now. 

I left a few small comments, then it's ready to 🚢

2023-03-09 17:03 UTC, emilylaguna commented on podcasts/New Search/Views/Results/SubscribeButtonView.swift
> +    private func subscribe() {
Hmm. While I think it's the correct approach it does feel like overkill for what this does. 

I'd say if we start using this in more places, or adding more functionality to it then we should make the model, but for now lets leave it as is.

2023-03-09 17:03 UTC, emilylaguna commented on podcasts/MainTabBarController.swift
> +                                                                 podcastUuid: podcastUuid)
We can remove the var here since it's not actually used. 

```suggestion
                if EpisodeLoadingController.needsLoading(uuid: episodeUuid), let podcastUuid {
                    let episodeController = EpisodeLoadingController(episodeUuid: episodeUuid,
                                                                 podcastUuid: podcastUuid)
```

2023-03-09 17:03 UTC, emilylaguna commented on podcasts/EpisodeLoadingController.swift
> +        UIView.animate(withDuration: duration, delay: 1.0) {
I did some testing and 0.3 seconds seems to work well. 

```suggestion
        UIView.animate(withDuration: duration, delay: 0.3) {
```

2023-03-09 18:52 UTC, merged