Search Improvements: search history
Automattic/pocket-casts-ios pull request #770
Opened 2023-03-09 19:10 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Adds the search history functionality.

<img src="https://user-images.githubusercontent.com/7040243/224128811-a855e9fc-d5ed-4c7f-9ba8-5e1fa942a18d.png" width="300">

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`

### Keeping track of search history

1. Go to discover
2. Perform a search
3. Tap in a few results (podcasts and episodes)
4. Tap "X" at the search bar
5. ✅ Your search history should be shown, including the episodes and podcasts you interacted with

### Interacting with search history

1. Tap a podcast
1. ✅ The podcast should show
1. Tap an episode
1. ✅ The episode should show
1. Tap the search term
1. ✅ The search should be performed

### Removing items

1. Tap "X" so you're back at search history
1. On any of the search history items, tap the "X" button
1. ✅ The entry should be removed
1. Tap "Remove all"
1. ✅ Everything should be removed

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-10 19:28 UTC, emilylaguna requested changes
🎉 Tested and all is working well. Left a few comments below.

2023-03-10 19:28 UTC, emilylaguna commented on podcasts/New Search/Model/SearchHistoryModel.swift
> +        if let entriesData = defaults.object(forKey: "SearchHistoryEntries") as? Data {
```suggestion
        if let entriesData = defaults.data(forKey: "SearchHistoryEntries") {
```

2023-03-10 19:28 UTC, emilylaguna commented on podcasts/New Search/Model/SearchHistoryModel.swift
> +        if let entriesData = defaults.object(forKey: "SearchHistoryEntries") as? Data {
Should we move the key to a constant?

2023-03-10 19:28 UTC, emilylaguna commented on podcasts/New Search/Model/SearchHistoryModel.swift
> +            }
[Nit] We could refactor this down to reduce the number of if lets

```suggestion
        self.entries = userDefaults.data(forKey: "SearchHistoryEntries").flatMap {
            try? JSONDecoder().decode([SearchHistoryEntry].self, from: $0)
        } ?? []
```

2023-03-13 12:47 UTC, leandroalonso commented on podcasts/New Search/Model/SearchHistoryModel.swift
> +        if let entriesData = defaults.object(forKey: "SearchHistoryEntries") as? Data {
Done in b7d09c5fccd57c3f25d93602ed72974b1f2e5419

2023-03-13 12:47 UTC, leandroalonso commented on podcasts/New Search/Model/SearchHistoryModel.swift
> +            }
Done in 700d27c3955da1e98d81e911c57aee047078ab9e

2023-03-14 19:40 UTC, emilylaguna approved these changes
:shipit:

2023-03-15 11:30 UTC, merged