Search Improvements: show podcasts and episodes in a standalone screen
Automattic/pocket-casts-ios pull request #771
Opened 2023-03-10 16:46 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Show podcasts and episodes on a standalone screen when tapping "Show All".

In this PR I also changed the max number of episodes to show in the search results view to 20 to match Android.

<img src="https://user-images.githubusercontent.com/7040243/224373279-69d7cf48-12b2-4ba1-bb20-bd8758aee721.png" width="300">

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`

### Showing all podcasts

1. Go to discover
2. Perform a search
3. Tap "Show All" for podcasts
4. ✅ A screen containing all the podcasts from the results should appear
5. Tap any podcast
6. ✅ The podcast screen should appear
6. Go back to the search history screen
6. The podcast you just opened should be there

### Showing all podcasts

1. Go to discover
2. Perform a search
3. ✅ A max of 20 episodes should be displayed in the search main screen
3. Tap "Show All" for episodes
3. ✅ All episodes should be there
3. Tap any episode
3. ✅ The episode screen should appear
6. Go back to the search history screen
6. The episode you just opened should be there

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-10 16:47 UTC, leandroalonso commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +struct InlineResultsView: View {
I'm not sure this name makes sense, open to suggestions.

2023-03-13 18:23 UTC, emilylaguna requested changes
Working as intended, left a couple comments below.

2023-03-13 18:23 UTC, emilylaguna commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +    var showPodcasts = true
What do you think about making this an enum and renaming it to `displayMode`? 

I think doing that would provide some extra context without needing to read the doc comment.

2023-03-13 18:23 UTC, emilylaguna commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +            .navigationBarTitle(Text(showPodcasts ? L10n.discoverAllPodcasts : "All Episodes"))
```suggestion
            .navigationBarTitle(Text(showPodcasts ? L10n.discoverAllPodcasts : L10n.discoverAllEpisodes))
```

2023-03-13 18:23 UTC, emilylaguna commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +struct InlineResultsView: View {
`SearchResultsListView`?

2023-03-13 18:47 UTC, leandroalonso commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +    var showPodcasts = true
Done in c556e99d677ea4777f9217f531bf28c8f3ba4225

2023-03-13 18:47 UTC, leandroalonso commented on podcasts/New Search/Views/Results/InlineResultsView.swift
> +struct InlineResultsView: View {
Yes! Done in 098ea0d148bfdb9c81ac99ddeb0c86bee02599bf

2023-03-14 19:46 UTC, emilylaguna approved these changes
🚢

2023-03-15 11:30 UTC, merged