Search Improvements: search from Podcasts and Discover
Automattic/pocket-casts-ios pull request #772
Opened 2023-03-10 17:47 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Search now works correctly from both "Podcasts" tab and "Discover" tab.

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`

### Independently search

1. Go to Podcasts
1. Search for something
1. ✅ Make sure results are appearing
1. Without closing this search, go to Discover
1. Make another search
1. ✅ Check Podcasts and Discover, they should display independently results based on your search
1. Dismiss both searches

### Redoing a search from History

1. Make sure search is appearing under Podcasts
1. Tap the search field
1. In the history, select any search term
1. Go to Discover
1. ✅ The search input should be clear
1. Tap on it
1. Select any search term
1. Go back to Podcasts
1. Teh search term should display the search term you selected on step 3

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-10 17:48 UTC, leandroalonso commented on podcasts/DiscoverViewController.swift
> +        setupSearchBar()
Had to move this below because adding the search controller as a child wasn't working when the call was before.

No idea why. 🙃

2023-03-13 18:35 UTC, emilylaguna requested changes
While testing I found that I am not able to get the search history to display again after my first search:

https://user-images.githubusercontent.com/793774/224797478-59eb0270-bdd6-4fff-a6d7-97c7c3b7c4b1.MP4

2023-03-13 19:00 UTC, leandroalonso commented
> While testing I found that I am not able to get the search history to display again after my first search:

I'm not able to reproduce that. 🤔

I've pushed a commit that maybe should fix that, but I'm not sure. Can you double-check, please?

2023-03-14 19:54 UTC, emilylaguna approved these changes
All working fine for me now. 🎉

2023-03-15 11:30 UTC, merged