Search Improvements: show local podcasts and folders
Automattic/pocket-casts-ios pull request #773
Opened 2023-03-13 17:20 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Show local podcasts and folders when searching from "Podcasts".

https://user-images.githubusercontent.com/7040243/224776262-de56c635-1704-43ce-889f-3dd595f42970.mp4

**UI is part of another task.**

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`
4. Login into an account with Plus, folders and subscribed podcasts

### Local podcasts and folders

1. Go to "Podcasts"
2. Search for a term that matches the name of your folders and podcasts
3. ✅ Your local podcasts and folders should appear at the beginning of "Podcasts" section. Also, after a while, a remote search is performed, and remote podcasts/folders is shown
4. Go to Discover
5. Search for the same
6. ✅ Only remote podcasts should be returned, no local results and/or folders

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-13 17:25 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +public struct PodcastFolderSearchResult: Codable, Hashable {
I don't like the idea of this representing a Podcast OR a Folder.

However, I tried encapsulating similar properties into a protocol and having both separated but didn't manage to succeed. Any ideas are appreciated.

2023-03-14 22:21 UTC, emilylaguna requested changes
Nice work, I left a few comments. 

I tried coming up with a different solution for the podcast/folder item, but wasn't able to come up with anything better.

2023-03-14 22:21 UTC, emilylaguna commented on podcasts/New Search/Model/SearchResultsModel.swift
> +        let allPodcasts = DataManager.sharedManager.allPodcasts(includeUnsubscribed: false)
I think we should clear the remote search results when doing another local search since this can cause the remote episodes to stay visible.

```suggestion
        clearSearch()
        let allPodcasts = DataManager.sharedManager.allPodcasts(includeUnsubscribed: false)
```

2023-03-14 22:21 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +public struct PodcastFolderSearchResult: Codable, Hashable {
hmmm. I tried a few ideas but nothing really worked out. I think we could do something like this though:

```
public struct PodcastFolderSearchResult: Codable, Hashable {
    public let uuid: String
    public let title: String
    public let author: String?
    public let kind: Kind

    public init?(from podcast: Podcast) {
        guard let title = podcast.title, let author = podcast.author else {
            return nil
        }

        self.uuid = podcast.uuid
        self.title = title
        self.author = author
        self.kind = .podcast
    }

    public init?(from folder: Folder) {
        self.uuid = folder.uuid
        self.title = folder.name
        self.author = nil
        self.kind = .folder
    }

    public enum Kind: Codable {
        case podcast, folder
    }
}
```

That way we can just switch on that which cleans up some of the if/else's

2023-03-15 00:02 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +public struct PodcastFolderSearchResult: Codable, Hashable {
So, I was thinking and since we have a lot of different kinds, I was thinking we could do something like this to generalize it even further:

```
public enum SearchItemType: String, Codable {
    case searchTerm = "search_term", episode, podcast, folder, unknown
}

protocol SearchItem {
    var kind: SearchItemType { get }
}

extension String: SearchItem {
    var kind: SearchItemType { .searchTerm }
}

extension EpisodeSearchResult: SearchItem {
    var kind: SearchItemType { .episode }
}

public struct PodcastFolderSearchResult: Codable, Hashable, SearchItem {
    ... 
    public var kind: SearchItemType
    ...
}

// Makes switching on the history easier too
struct SearchHistoryEntry: Codable, Hashable {
    var searchTerm: String?
    var episode: EpisodeSearchResult?
    var podcast: PodcastFolderSearchResult?

    var kind: SearchItemType {
        let items: [SearchItem?] = [searchTerm, episode, podcast]
        return items.compactMap { $0 }.first?.kind ?? .unknown
    }
}
```

Wdyt?

2023-03-15 12:04 UTC, leandroalonso commented
@emilylaguna thanks for the suggestion! I adapted the code to your idea.

2023-03-15 17:52 UTC, emilylaguna approved these changes
Code looks good now, I noticed a couple issues which I think we can tackle in a different PR, let me know what you think.

**Issue 1:**

If I tap on the Show All when a Folder is displayed the folder doesn't display correctly:

<img src="https://user-images.githubusercontent.com/793774/225398452-02d0c99b-0edd-478e-b7a6-ba4a3283703f.PNG" width="200" />

**Issue 2:** 

Also if I tap on the Show All while the remote results are loading I get this:

<img src="https://user-images.githubusercontent.com/793774/225398784-be0ff36f-399b-4a72-8493-2e88f56d8ce1.PNG" width="200" />

it updates correctly when the results load.

2023-03-15 19:00 UTC, leandroalonso commented
@emilylaguna I added those issues in #709

2023-03-15 19:00 UTC, merged