Search Improvements: UI refinements
Automattic/pocket-casts-ios pull request #778
Opened 2023-03-15 19:13 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

This PR fixes the following issues:

* It makes search and search history work well with any theme
* It fixes the layout for iOS 15 (by removing usage of `List`)
* It reacts to the mini player appearing/disappearing
* Dismiss keyboard when scrolling
* On iPad, the podcast carousel show more podcasts
* Change the label of search input

I also removed manual injections in favor or `@EnvironmentObject`.

One important thing is that I wasn't able to make the carousel exactly like the designs. That would require adding a library, and I'd rather prefer not to do so for this very specific part.

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
3. Change the app Build Configuration to `Staging`

### Local podcasts and folders

1. Test the search using different themes and make sure everything appears correctly
2. Do the same, but on an iOS 15 simulator
3. Search for something and play/remove the miniplayer to see that the view now reacts to it being added/removed
4. Scroll the results and see that the keyboard is dismissed
5. Test the search on iPad
6. Check that the search label now says "Search podcasts or add RSS URL"

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-15 19:18 UTC, leandroalonso commented on podcasts/PCSearchBarController.swift
> +    var placeholderText = L10n.searchLabel
New label applies to the current search so I think we can just enable it.

2023-03-17 22:33 UTC, emilylaguna requested changes
Looking good. I noticed a few issues that I noticed below and made a few suggestions. 

Let me know what you think.

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/New Search/Views/Results/SearchResultsListView.swift
>                  LazyVStack(spacing: 0) {
We're using this same structure in a few different places what do you think about making a wrapper view for this?

```
struct SearchListView<Content: View>: View {
    @EnvironmentObject var theme: Theme

    let content: () -> Content

    public init(@ViewBuilder _ content: @escaping () -> Content) {
        self.content = content
    }

    var body: some View {
        VStack(spacing: 0) {
            ThemedDivider()

            ScrollView {
                LazyVStack(spacing: 0) {
                    content()
                }
            }
        }
        .background(AppTheme.color(for: .primaryUi02, theme: theme))
        .applyDefaultThemeOptions()
    }
}
```

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/New Search/SearchResultsViewController.swift
> +        UIScrollView.appearance().keyboardDismissMode = .none
This doesn't seem to be working for me. When I inspected the value further in the view stack it's always set to none. 

https://user-images.githubusercontent.com/793774/225994847-588838ec-0ff7-41c5-b2a8-1ad8269b2245.MP4

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/New Search/Views/SearchView.swift
> +            })
Since as we add more SwiftUI this will most likely need to be used elsewhere, what do you think about moving this to the Style.swift or a new file in the SwiftUI folder?


I did notice an issue with this though: If I open the keyboard the padding appears above it. 

https://user-images.githubusercontent.com/793774/225977261-abdf137f-63be-4a55-86c8-956f7a2065f4.MP4

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/PCNavigationController.swift
> +        } else if topViewController is AnyUIHostingViewController, topViewController?.preferredStatusBarStyle == .default {
Oh interesting! Good idea. 💯

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/New Search/Views/Results/PodcastCarouselView.swift
> +                                    .padding(.all, 10)
I think we can refactor this code a bit to do something like:

```
let podcastsPerPage = 2
let pages = searchResults.podcasts.chunked(into: podcastsPerPage)
ForEach(pages, id: \.self) { page in
    HStack(spacing: 10) {
        ForEach(page, id: \.self) { podcast in
            PodcastResultCell(result: podcast)
        }

        if page.count < podcastsPerPage {
            Rectangle()
                .opacity(0)
        }
    }.padding(10)
}
```

2023-03-17 22:33 UTC, emilylaguna commented on podcasts/New Search/Views/Results/PodcastCarouselView.swift
> +                            .aspectRatio(1, contentMode: .fit)
The aspect ratios here are messing up the display on the iPhone SE and 8 Plus:


https://user-images.githubusercontent.com/793774/226061795-7619652d-4f13-4fba-8bae-6052d9b464dc.mp4

2023-03-21 00:15 UTC, leandroalonso commented on podcasts/New Search/Views/SearchView.swift
> +            })
Done in 287704442eb063438425d398173fbb3471aadc1f

2023-03-21 00:40 UTC, leandroalonso commented on podcasts/New Search/Views/SearchView.swift
> +            })
I think Styles isn't the correct place so I moved it to Utils: 52eb8e172bdd0a632b8a83b62109c122745d48c5

2023-03-21 00:41 UTC, leandroalonso commented on podcasts/New Search/SearchResultsViewController.swift
> +        UIScrollView.appearance().keyboardDismissMode = .none
I changed how that works in 4b63cfcf6fb925499752a0631f9225759040e2fa

It would be good to test on iOS 15 and 16. :)

2023-03-21 00:42 UTC, pocketcasts commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
DismissKeyboardOnScroll.swift | 23 | Files should have a single trailing newline. (trailing_newline)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-03-23 19:30 UTC, leandroalonso commented on podcasts/New Search/Views/Results/PodcastCarouselView.swift
> +                            .aspectRatio(1, contentMode: .fit)
I've gone ahead and changed the carousel to be a simple `ScrollView` so this issue is now fixed. :)

2023-03-23 19:31 UTC, leandroalonso commented
@emilylaguna ready for another review.

2023-03-29 19:11 UTC, emilylaguna approved these changes
Nice work! I found a couple small issues but should be addressed in a future PR:

1. The History seems to be saving as I type
2. I have a folder in my history but it's been deleted but still appears and tapping it doesn't do anything

2023-03-29 19:23 UTC, leandroalonso commented
@emilylaguna thanks! Added both in #709

2023-03-29 19:23 UTC, merged