Search Improvements: fix some issues
Automattic/pocket-casts-ios pull request #780
Opened 2023-03-16 15:36 UTC by leandroalonso

| 📘 Project: #709 |
|:---:|

Fix these issues:

1. Folders not appearing on the list view
2. No loading indicator on the list view
3. History out of sync between DIscover/Podcasts search
4. Carousel position being reset when showing local results

## To test

### Before everything

1. Run the app
2. Go to Profile > Settings > Beta Features > enable `newSearch`
4. Login into an account with Plus, folders and subscribed podcasts

Then:

1. Search for a folder name under Podcasts
2. Tap "Show All"
3. ✅ The folder should appear and when tapped it should be shown
4. Search again for something
5. Quickly go to "Show All" and see that there's a loading indicator
6. Go back, and search for something that would return podcasts/folders
6. Swipe in the carousel
6. ✅ When remote results arrive, the carousel should not reset its position
6. Dimiss the search
6. Open the search history in both Discover and Podcasts
6. Remove one search history item and check that is reflected in the other
6. Search for a URL, ie.: https://podcast.emily.tools/
7. ✅ The podcast correspondent to the URL should be returned and no episodes are shown

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-17 22:56 UTC, emilylaguna requested changes
Nice work, Left a few comments below.

2023-03-17 22:56 UTC, emilylaguna commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            Text(result.author)
Should we default the author to Folder for folders so it will display like it does on the search history?

2023-03-17 22:56 UTC, emilylaguna commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            .allowsHitTesting(false)
The rounded corners are missing on this view. 
<img width="74" alt="Screen Shot 2023-03-17 at 6 38 34 PM" src="https://user-images.githubusercontent.com/793774/226064832-edbd3832-7627-4a7d-8c76-ea5004142452.png">

2023-03-17 22:56 UTC, emilylaguna commented on podcasts/New Search/Views/Results/PodcastCarouselView.swift
> +                    if (searchResults.isSearchingForPodcasts && !searchResults.isShowingLocalResultsOnly) || (searchResults.isShowingLocalResultsOnly && searchResults.podcasts.isEmpty) {
This is pretty long, wdyt about moving it into a property to improve readability?

2023-03-29 13:17 UTC, leandroalonso commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            .allowsHitTesting(false)
Done in d6cb51885faa20ca8e2e8a837ce5928cfc2a4746

2023-03-29 13:17 UTC, leandroalonso commented on podcasts/New Search/Views/Results/PodcastCarouselView.swift
> +                    if (searchResults.isSearchingForPodcasts && !searchResults.isShowingLocalResultsOnly) || (searchResults.isShowingLocalResultsOnly && searchResults.podcasts.isEmpty) {
Done in aa5c3e6166b6c24362455392812e81009acb25c8

2023-03-29 13:17 UTC, leandroalonso commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            Text(result.author)
Not sure I'm following. What do you mean?

2023-03-29 20:04 UTC, emilylaguna approved these changes
nice work, left 1 small comment below.

2023-03-29 20:04 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +    let searchResults: [PodcastFolderSearchResult]
Can you add some documentation about what each value represents and when podcast would be null?

2023-03-29 20:09 UTC, emilylaguna commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            Text(result.author)
Sorry I meant should we have the author appear as `L10n.folder` here so it will display Folder instead of blank label? Similar to what we're doing on the search history cell.

2023-03-30 12:34 UTC, leandroalonso commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +    let searchResults: [PodcastFolderSearchResult]
Done in 9690382d0c4e29c6a949ad2c02125a9b7503cf2a

2023-03-30 12:39 UTC, leandroalonso commented on podcasts/New Search/Views/Results/SearchResultCell.swift
> +                            Text(result.author)
Done in 14452ad187bb5c8b398e7c93a84fafca5a1c69ff

2023-03-30 13:04 UTC, merged