Fix Auto Add to Up Next reset bug
Automattic/pocket-casts-ios pull request #788
Opened 2023-03-28 05:58 UTC by mrpolanco

Fixes #712 

When using the "Auto Add to Up Next" feature, there's a bug that occurs when choosing the Auto Add behavior. By default, podcasts selected for "Auto Add to Up Next" are podcasts at the bottom of the Up Next list. Users can change this behavior and choose podcasts to be added to the top of the Up Next list.

Users can also add all their podcasts to the Up Next lists using the Select All feature. The bug occurs when a user has all their podcasts selected to be added to Up Next. If the user deselects and re-selects a podcast on the list, all podcasts revert to the default configuration, which is to be added to the bottom of the Up Next list. 

This PR addresses this issue by keeping the individual podcasts as configured by the user, even when selecting and deselecting individual podcasts.

## To test

1. Subscribe to a few podcasts.
2. Tap Profile, then the Gear icon to go to Settings.
3. Tap Auto Add to Up Next menu
4. Tap the "0 Podcasts Chosen" menu
5. Select All podcasts and return to the previous menu
6. Change individual settings for a few podcasts to Add to Top
7. Tap the "# Podcasts Chosen" menu

![Flow - iPhone SE (2nd generation-side](https://user-images.githubusercontent.com/81433983/228139623-addb749c-015c-4eb0-ae7f-fed2fe3c1a4f.png)

8. Tap to deselect one podcast from the list, then tap to select again - on the current version, doing so resets all podcasts to Add to Bottom
9. Verify that this PR allows settings to remain

![Flow 2 - iPhone SE (2nd generation)](https://user-images.githubusercontent.com/81433983/228139974-6c469e40-148a-474e-a40b-7a0b694265be.png)

Note: The podcast that was deselected and reselected will be reset to Add to Bottom. This is intended behavior when an unselected podcast is first selected.

## Checklist

- [✅] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [✅] I have considered adding unit tests for my changes.
- [✅] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-03-29 18:47 UTC, emilylaguna requested changes
Hey @mrpolanco, nice work on identifying and fixing this bug! 

I left some comments below on how we can improve the performance of the update process a bit. 

I think it would also be good to add a unit test for this process, what do you think?

2023-03-29 18:47 UTC, emilylaguna commented on podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
> +            DataManager.sharedManager.saveAutoAddToUpNextForAllPodcasts(autoAddToUpNext: setting)
The setting var only looks to be used here wdyt about removing it?

```suggestion
            DataManager.sharedManager.saveAutoAddToUpNextForAllPodcasts(autoAddToUpNext: AutoAddToUpNextSetting.off.rawValue)
```

2023-03-29 18:47 UTC, emilylaguna commented on podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
> +            }
Sorry for the long comment. 

In my testing I found this causes a considerable lag when running on databases with lots of podcasts. I currently have 200 that I'm subscribed to and my phone hangs for about a second when running through this. 

Did some digging on why and since we're looping through the podcasts and calling `DataManager.sharedManager.saveAutoAddToUpNext` for each of them results in:

- Making a [DB call to update](https://github.com/Automattic/pocket-casts-ios/blob/cef84ace4cb45ad3d9fd39fc27f87c50ca3af8e9/Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift#L472) the saved value
- Making another [DB call to refresh](https://github.com/Automattic/pocket-casts-ios/blob/cef84ace4cb45ad3d9fd39fc27f87c50ca3af8e9/Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift#L479-L500) our internal podcast cache which includes ALL the podcasts stored in the database, not just subscribed ones
- The update cache call also needs to update the internal cache array using a [synchronous call](https://github.com/Automattic/pocket-casts-ios/blob/cef84ace4cb45ad3d9fd39fc27f87c50ca3af8e9/Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift#L493) which adds extra time the rest of the queries 
- The update cache call needs to convert all the DB values to Podcast objects again

If we run the code through the Time Profiler we can see the breakdown of the process, and see the majority of the time spent is just in the rebuilding of the cache and converting the DB values to Podcast objects again. 


<img width="922" alt="Screen Shot 2023-03-29 at 2 14 56 PM" src="https://user-images.githubusercontent.com/793774/228630822-ae33f17c-4e54-4050-a744-f8bd3193879a.png">

2023-03-29 18:47 UTC, emilylaguna commented on podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
> +            }
I think based on what we know from the above we can reduce this down to 2 total queries by moving the updating of all the podcasts from the client to the database by:

1. Adding a new method to the PodcastDataManager similar to `saveAutoAddToUpNextForAllPodcasts` but instead takes a podcasts array and passes their `UUID`'s in the WHERE query
2. Updating this to filter the podcasts similar to what we have now but adding an `.isSubscribed()` check
3. Passing the podcasts to the new method

I made a quick idea branch demonstrating this here: https://github.com/Automattic/pocket-casts-ios/compare/issue/712_Auto_Add_to_Up_Next_bug...idea/712-auto-add-reset-bug

Let me know what you think.

2023-03-29 19:53 UTC, mrpolanco commented on podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
> +            DataManager.sharedManager.saveAutoAddToUpNextForAllPodcasts(autoAddToUpNext: setting)
Thought about readability, but you're right, it can be done away with :)

2023-05-31 02:44 UTC, mrpolanco commented on podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
> +            }
Tested the proposed method on this branch by adding 250 podcasts and using the Time Profiler to test db queries. It worked splendidly, reducing cache rebuild time from 494.0 ms to 2.0 ms 🙌🏼

**Initial reset bug fix:**

<img width="972" alt="Initial reset bug fix" src="https://github.com/Automattic/pocket-casts-ios/assets/81433983/2a283514-5b15-4796-8bd2-2b04b9b5e1ee">

**Bug fix refactor:**

<img width="972" alt="Bug fix refactor" src="https://github.com/Automattic/pocket-casts-ios/assets/81433983/57ef8a43-77e8-43a4-9b6c-b6e10480cc2b">

2024-02-03 02:29 UTC, merged