Make author optional to avoid decoding issues
Automattic/pocket-casts-ios pull request #810
Opened 2023-04-07 13:30 UTC by leandroalonso

Fixes search not returning results in case author is not available.

## To test

1. Run the app
2. Search for "Knifecast"
3. ✅ Podcasts results should appear

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-04-07 21:00 UTC, emilylaguna requested changes
This fixes the results not appearing, however this got me curious so I did a check and it is possible for title to be nil as well. 

Can we add that check as well?

2023-04-07 21:00 UTC, emilylaguna commented on Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
> +        let envelope = try! decoder.decode(PodcastsSearchEnvelope.self, from: data)
```suggestion
        let envelope = try decoder.decode(PodcastsSearchEnvelope.self, from: data)
```

2023-04-10 12:37 UTC, leandroalonso commented
@emilylaguna changed `title` to be optional too.

2023-04-10 19:37 UTC, emilylaguna approved these changes
🚢

2023-04-10 21:01 UTC, geekygecko commented
Can we help on the server by always returning an empty string in the author field for now?

2023-04-10 21:58 UTC, leandroalonso commented
@geekygecko This only affects the new search, so there is no need to do that (the previous search works just fine!)

2023-04-10 21:58 UTC, merged