Patron: update upgrade screen
Automattic/pocket-casts-ios pull request #833
Opened 2023-04-25 13:04 UTC by leandroalonso

Updates the new upgrade screen to display prices right away and allow the purchase without the need to show the modal.

## To test

### Pre-testing setup:
1. Open the Xcode Project
3. Hit <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>,</kbd> to open the Scheme editor
4. Click the options tab
5. Select the `Pocket Casts Configuration.storekit` file in the StoreKit configuration dropdown

### Test the current flow

1. Enable the `patron` flag in `FeatureFlag.swift`
2. Do a clean install of the app
3. Go through the whole onboarding process and buy any plan
4. ✅ Make sure you see the confetti screen at the end
5. Go to Settings > Developer > tap "Set to No Plus"
6. Go to Podcasts > tap the Folder button
7. Buy any plan
8. ✅ Make sure you see the confetti screen
9. On Xcode, go to Debug > StoreKit > Manage Transactions
10. Delete Everything
11. Display the `.sorekit` file on Xcode
12. Go to Editor > Fail Transactions > select any failure except the "unknown"
13. Re-run the app
13. Go to Settings > Developer > tap "Set to No Plus"
6. Go to Podcasts > tap the Folder button
7. Buy any plan
1. ✅ An error should be displayed

### Test messages

1. Open the `.storekit` file
2. Add free trial in all 4 available tiers, choose anything you want but make sure they're different
13. Re-run the app
13. Go to Settings > Developer > tap "Set to No Plus"
1. ✅ Make sure the correct prices and trial period are shown

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-04-25 13:08 UTC, leandroalonso commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +        Text(purchaseTerms[safe: 0] ?? "") + Text("[\(purchaseTerms[safe: 1] ?? "")](https://support.pocketcasts.com/article/privacy-policy/)").underline() + Text(purchaseTerms[safe: 2] ?? "") + Text
I cannot use a constant for the URL here, unfortunately. If I do that, the link doesn't work.

2023-04-25 16:16 UTC, emilylaguna requested changes
Overall this is working really well, nice job!

While testing I noticed a few issues which I noted below. 

For the layout issues I think we can fix those in another PR since I they're kind of outside the scope of this one.
---

There's a bug that I saw a few times during testing where the model loads and is waiting for the prices but will display blank values.

I can repro easily by disabling the `IapHelper.shared.requestProductInfo` call in the AppDelegate.


<img width="160" src="https://user-images.githubusercontent.com/793774/234329712-cfceb5d7-c562-4ee3-b1e4-bc02cd5b0267.png">

It looks like this is happening because the PlusPricingInfoModel.pricingInfo is only being set on init, so if the pricing is not available at init then it won't be updated. 

I think we can fix that by reloading when setting the `priceAvailability` to available.

---

On the iPhone 14 Pro the content is aligned to the bottom and leaves large spacing at the top of the view.
 
<img width="160" src="https://user-images.githubusercontent.com/793774/234333305-6cfe7259-cab1-48a9-bf45-881ff5b20542.png">

---

On the smallest device that we support (iPod Touch 7th Gen) the view layout breaks:

<img width="160" src="https://user-images.githubusercontent.com/793774/234336825-72f65896-43c3-4878-adf3-f84d9250bcad.png">

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusLandingViewModel.swift
> +        if let _ = product.freeTrialDuration {
```suggestion
        if product.freeTrialDuration != nil {
```

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/PlusLandingViewModel.swift
> +            UpgradeLandingView(purchaseModel: purchaseModel)
Since we're passing the other view model via an environment object, should we do the same thing for the purchase model?

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +    @State private var loadingPrices = true
This doesn't seem to be used?

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +        Text(purchaseTerms[safe: 0] ?? "") + Text("[\(purchaseTerms[safe: 1] ?? "")](https://support.pocketcasts.com/article/privacy-policy/)").underline() + Text(purchaseTerms[safe: 2] ?? "") + Text
You can wrap the markdown in `.init` to fix that:

```
        let privacyPolicy = ServerConstants.Urls.privacyPolicy
        let termsOfUse = ServerConstants.Urls.termsOfUse

        Text(purchaseTerms[safe: 0] ?? "") +
        Text(.init("[\(purchaseTerms[safe: 1] ?? "")](\(privacyPolicy))")).underline() +
        Text(purchaseTerms[safe: 2] ?? "") +
        Text(.init("[\(purchaseTerms[safe: 3] ?? "")](\(termsOfUse))")).underline()
```

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +    var termsAndConditions: some View {
When I'm in dark mode the text disappears:

<img width="320" src="https://user-images.githubusercontent.com/793774/234323486-c2f4a481-2f58-4e16-acd1-dd46c16f5c6e.png">

2023-04-25 16:16 UTC, emilylaguna commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +                    .opacity(0.64)
No need for the Group here. 

```suggestion
                    termsAndConditions
                    .font(style: .footnote).fixedSize(horizontal: false, vertical: true)
                    .tint(.black)
                    .opacity(0.64)
```

2023-04-25 16:34 UTC, leandroalonso commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +    @State private var loadingPrices = true
Removed in 8c3ced2b7e93e198d18b3e29beb7f91e6605f8bc

2023-04-25 16:35 UTC, leandroalonso commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +    var termsAndConditions: some View {
Done in 4b3834831c223c2f07d4c617892356291ac99613

2023-04-25 16:35 UTC, leandroalonso commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +                    .opacity(0.64)
Ops, left it by mistake, done in a1c6d072c374a2a84c66fa733c843db5cabd8b69

2023-04-25 16:44 UTC, leandroalonso commented on podcasts/Onboarding/Plus/PlusLandingViewModel.swift
> +            UpgradeLandingView(purchaseModel: purchaseModel)
I don't think `PlusPurchaseModel` needs to be an environment object but it's better to be consistent, changed in 3525856a458b28992e0bba01b533d3a85df5b3d0

2023-04-25 17:02 UTC, leandroalonso commented on podcasts/Onboarding/Plus/UpgradeLandingView.swift
> +        Text(purchaseTerms[safe: 0] ?? "") + Text("[\(purchaseTerms[safe: 1] ?? "")](https://support.pocketcasts.com/article/privacy-policy/)").underline() + Text(purchaseTerms[safe: 2] ?? "") + Text
Awesome, thanks! Done in d8bbfc8548940e7b2306ad9833b54cd63c7b152c

2023-04-25 18:15 UTC, leandroalonso commented
@emilylaguna ready for another look!

I changed the layout a bit so the examples you mentioned should be fixed. We have another possibility on fixing that by adding a scroll view on the whole screen but I'll wait for some feedback before doing this change (and we can do in another PR).

2023-04-26 17:10 UTC, emilylaguna requested changes
This is working on smaller devices much better now. 

On the iPhone SE the paging indicator is appearing on top of the button which looks a bit odd. I wonder if on smaller devices we should hide the indicator to prevent this? 

<img width="289" alt="Screen Shot 2023-04-26 at 1 07 22 PM" src="https://user-images.githubusercontent.com/793774/234651153-da6b967f-bf95-4f8e-950f-c7fc3440456d.png">

Also, while testing the logged out flow I found that if I try to purchase from an upsell dialog I am not able to continue and instead get an error.

2023-04-26 17:47 UTC, leandroalonso commented
@emilylaguna fixed!

I also changed the page indicator to not appear in case of scrollable content.

2023-04-26 18:38 UTC, emilylaguna approved these changes
Looks good, the logged in issue is still there but we can address that in another PR. 

🚢

2023-04-26 19:58 UTC, merged