Episodes Autoplay: play the next episode
Automattic/pocket-casts-ios pull request #932
Opened 2023-06-28 16:18 UTC by leandroalonso

Adds the autoplay feature to the app.

## To test

### Flag disabled

1. Run the app and make sure the `autoplay` feature flag is **disabled**
2. Clear your Up Next queue
3. Play any episode and move the scrubber to the end
4. ✅ Nothing should autoplay after the episode finishes
5. **Enable** the `autoplay` feature flag, go to Profile > Settings > disable "Continuos Playback"
3. Play any episode and move the scrubber to the end
4. ✅ Nothing should autoplay after the episode finishes

### Flag enabled

#### Empty Up Next

1. Run the app and make sure the `autoplay` feature flag is **enabled** and Profile > Settings > enable "Continuos Playback" 
2. Make sure your Up Next queue is **empty**

Then, use this table as a guide for testing:

| Play an episode from | What should happen after the current episode finishes |
| --------------------- | ------------------------------------------------------ |
| Any podcast screen | The next episode should play (and the app will respect the order you defined) |
| A filter | The next episode in the filter should play |
| Starred screen | The next starred episode should play |
| Listening History | Nothing should be played after the current episode finishes |
| Files | The next episode should play |
| Downloads | The next downloaded episode should play |

#### Not Empty Up Next

1. Add two or three episodes to your Up Next
2. Play them til the end (moving the scrubber to the very end)
3. ✅ After the last one finishes playing nothing should happen

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-06-28 16:18 UTC, leandroalonso commented on podcasts/PodcastViewController+TableData.swift
> +                cell.playlist = .podcast(uuid: podcast.uuid)
Curiously, `listEpisode.episode.uuid` returns a wrong UUID 🫠

2023-06-29 20:32 UTC, emilylaguna requested changes
So far this is working well, I hit one issue when playing podcasts but elsewhere it seems to be working. 

However I am still testing this fully but I figured I would submit some changes.

2023-06-29 20:32 UTC, emilylaguna commented on podcasts/EpisodesDataManager.swift
> +                return Array(episodes(for: podcast).compactMap { $0.elements as? [ListEpisode] }.joined()).map { $0.episode }
I ran into an issue where the autoplay wouldn't work when played from the podcast details when my podcast is grouped by season and sorted newest to oldest. 

After some digging it looks like the data structure returned is:

```swift
[
    ArraySection("Search", [ListHeader()]),
    ArraySection("episodes", [
        ListHeader("No Season"),
        ListEpisode()
        ListEpisode(),
        .....
        ]
    )
]
```

This means that the first compactMap will return nil for the episodes section because not all items are ListEpisodes. 

We can fix this and refactor the code to be a bit faster by using a flatMap to flatten the array, and validating each element of the array.

```suggestion
                return episodes(for: podcast).flatMap { $0.elements.compactMap { ($0 as? ListEpisode)?.episode } }
```

2023-06-29 20:32 UTC, emilylaguna commented on podcasts/EpisodesDataManager.swift
> +            return Array(downloadedEpisodes().compactMap { $0.elements }.joined()).map { $0.episode }
We can skip the joining/Array casting step by using `flatMap`:

```suggestion
            return downloadedEpisodes().flatMap { $0.elements.map { $0.episode } }
```

2023-06-29 20:32 UTC, emilylaguna commented on podcasts/EpisodesDataManager.swift
> +                return episodes(for: filter).compactMap { $0.episode }
[nit] since `episodes(for: filter)` is returning an array without any nil items we can just use `map` here. 


```suggestion
                return episodes(for: filter).map { $0.episode }
```

2023-06-29 20:32 UTC, emilylaguna commented on podcasts/PlaybackManager.swift
> +            }
Wdyt about moving this code block into its own method to increase its visibility

2023-06-29 20:32 UTC, emilylaguna commented on podcasts/AutoplayHelper.swift
> +        if let lastPlaylist = lastPlaylist {
```suggestion
        if let lastPlaylist {
```

2023-06-29 20:35 UTC, emilylaguna commented on podcasts/EpisodesDataManager.swift
> +                return episodes(for: filter).compactMap { $0.episode }
.map is also slightly faster when processing lots of items than .compactMap

<img width="516" alt="Screenshot 2023-06-29 at 4 33 42 PM" src="https://github.com/Automattic/pocket-casts-ios/assets/793774/604fc3e4-ab2d-4056-8e52-614869ab281c">

2023-06-30 18:02 UTC, leandroalonso commented on podcasts/PlaybackManager.swift
> +            }
Done in 1d75527be9381ac105497eb8e8cbcf81ea3dbab6

2023-06-30 19:02 UTC, emilylaguna approved these changes
I've been testing this and its been working well! Nice job.

2023-06-30 19:37 UTC, merged