Adding share extension for importing OPML
Automattic/pocket-casts-ios pull request #947
Opened 2023-06-30 22:10 UTC by yaelirub

currently, even though we already have the code that handles OPML files, but the app doesn't appear as an option in the share sheet and I have to scroll to More and then search Pocket Casts among many other apps

https://github.com/Automattic/pocket-casts-ios/assets/1335657/876c97c7-6bbf-4abe-a47b-eb8c99cfff89

This PR adds a share extension so that the app shows up on OPML shares (exports). 
Please note that I left the boilerplate code in `ShareExtensionViewController` as our app handles opml files in `handleOpenUrl`

With this change:

https://github.com/Automattic/pocket-casts-ios/assets/1335657/8323f7bc-3dde-43c3-8cea-4384eca1014f

## To test
Steps to test your PR.
Export OPML files from other apps and see Pocket Casts as an option in the apps row of the share sheet.

## Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `CHANGELOG.md` if necessary.
- [x] I have considered adding unit tests for my changes.
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

2023-06-30 22:12 UTC, pocketcasts commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
ShareViewController.swift | 21 | Lines should not have trailing whitespace. (trailing_whitespace)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-07-03 16:04 UTC, leandroalonso requested changes
@yaelirub the `MainInterface.storyboard` is still missing. 😬

However, I manually added it and I wasn't able to test it on a real device because we don't have the certificate for the share extension configured. I guess you're probably able to run because you're an admin.

I asked our friends from App Infra to add the certificate for us and once they do we can make a few changes here so CI will be green and we'll be able to test it. :)

2023-07-03 18:58 UTC, yaelirub commented
Thanks Leandro!

2023-07-06 13:42 UTC, leandroalonso commented
I was able to run the PR on a real device but I don't see the icon appearing. :(

I wonder if the new app group ID had any influence on this. 🤔 

Just to keep you all posted I plan to get back to this task once I finish some other PRs.

2023-07-11 21:15 UTC, leandroalonso approved these changes

2023-07-11 21:15 UTC, leandroalonso commented on Share Extension/ShareViewController.swift
> +
```suggestion
```

2023-07-12 07:50 UTC, merged